### ISSUE TITLE
Stage Depth Navigation

### ISSUE THREAD

**Issue by sbsoso0411** [rnbwdev/rnbw#199]
- [x] Multiple Selection (multi-level)
- [x]  Select multiple elements at once, so I ca
    - [ ]  Drag them to a specific level altogether.
    - [x]  Wrap them by grouping them into a div at the same level
    - [x]  Cut, Copy, and Paste them.

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 I think we have achieved this. Wdyt?

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 StageView-DnD is the one we should fix.
but yes. I think we can close this and create a new issue for that later.
