### ISSUE TITLE
"Cut" (elements) function doesn't work properly

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#242]
CMD+X (and then CMD+V) are working for the selected elements.
yet elements doesn't vanishes when the actual "cut" is performed.

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/c3a94ef7-f518-4c18-9875-e493f37891bb)

https://github.com/rnbwdev/rnbw/assets/38177419/0fdf907a-cf92-49d2-bd6d-82e12afadcde

**Comment by VictoriaShyika** [comment]
I familiarized myself with the project and saw the peculiarity that the cutting function inserts the component at the same level on which the selected component is located.

After testing the operation of the application, cutting using the keyboard (CMD+X, CMD+V) works https://www.loom.com/share/98643f30832e4322b87b1af95cf6ab3e , but when using the modal menu (key W) - not.
Can you explain your desired result?

**Comment by VictoriaShyika** [comment]
I fixed some functional problems and we have next result: 
https://www.loom.com/share/de722bf51a66402ba10e8b7a6894a5d4

Is this a required behavior?

**Comment by edenvidal** [comment]
@VictoriaShyika, this is "copy". it is not "cut".
"cut" is when the element(s) is deleted from the selection. you know - "cut" 💁‍♂️

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika this functionality already works the way you showed it.

For the actual behavior, check how it happens in figma.

When you cut the element disappears along with its node. And when you paste it is visible back again to wherever you pasted it.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika 

There's a little tweak needed in the sequence it happens.

Now:
ctrl+x: copy 
ctrl+v: delete + paste

Desired:
ctrl+x: copy + delete
ctrl+v: paste

**Comment by VictoriaShyika** [comment]
> @VictoriaShyika this functionality already works the way you showed it.
> 
> For the actual behavior, check how it happens in figma.
> 
> When you cut the element disappears along with its node. And when you paste it is visible back again to wherever you pasted it.

Could you provide figma link for me?

**Comment by edenvidal** [comment]
@VictoriaShyika, everything you mentioned might be true when working without history events.
in rnbw, everything is a history event. so if you hit cmd+z after doing a "cut" it'll get back. whether its a file or an element.

**Comment by VictoriaShyika** [comment]
Ok, I got it.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika by figma I meant how Figma as a design tool does it.

**Comment by atulbhatt-system32** [comment]
> > @VictoriaShyika this functionality already works the way you showed it.
> > For the actual behavior, check how it happens in figma.
> > When you cut the element disappears along with its node. And when you paste it is visible back again to wherever you pasted it.
> 
> Could you provide figma link for me?

updated the issue description check the video for figma illustration

**Comment by atulbhatt-system32** [comment]
Seems like after refactoring the functionality of cut paste is broken. @VictoriaShyika can you verify the same.
