### ISSUE TITLE
Decoupling Actions

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#245]
### Decoupling and modularizing the codebase

**Expectations:**

1. Group different lines of groups into reusable functions with proper names. A person should be able to get overview of what the group of line of code does just by looking at the function names.

2. If somewhere some configs are used inline and they can be extracted out to a variable, do it. Below is example:
```
        props={{
              canDragAndDrop: true,
              canDropOnFolder: true,
              canDropOnNonFolder: true,
              canReorderItems: true,

              canSearch: false,
              canSearchByStartingTyping: false,
              canRename: false,
            }}
```

3. Create Custom Hook If it's beneficial to separate the concerns of presentational and business logic.

4. Following DRY principle is important but make sure it doesn't make our code tightly coupled. Sometimes it's better to have same code written twice if the LOCs are not that much.

#### Modules to cover
  - [x] #251
  - [x] #252
  - [ ] #253
  - [ ] #254
  - [ ] #257
  - [ ] #258

**Comment by MadDog1994** [comment]
comment
