### ISSUE TITLE
at the initial state. the active element is selected on the tree, but not selected on stage and code.

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#247]
- [ ] sync the code/stage/tree selection at the lower level (so that we don't have to define the correlation between them in many other cases)

**Comment by MadDog1994** [comment]
I'm going to make changes that will do the following:
when opening the project, the element selected in the tree will be displayed on the stage and in the code

**Comment by edenvidal** [comment]
@MadDog1994 i think we can implement it.

regardless - 
@atulbhatt-system32 should we define this at a lower level? maybe we should define it so that - whenever an element is selected, it is selected anywhere. since there are many more cases in which there's a fallback to "select" (some are covered, but i'm not sure how DRY is it).
how does it work now?

**Comment by atulbhatt-system32** [comment]
@edenvidal  I think we can ask @MadDog1994 to implement the same and he can improve the whatever code he goes through while implementing it and see what the edge cases are already covered.

**Comment by MadDog1994** [comment]
I made the changes, now when the user opens the project we can see that the selected element on the tree is also selected on the code and on the stage
