### ISSUE TITLE
After editing the code once, the codeview doesn't sync anymore with the nodes on stage or nodetree.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#266]

**Comment by VictoriaShyika** [comment]
Set up sync after code editing first time

**Comment by edenvidal** [comment]
@VictoriaShyika shall i show you examples from a user-experience perspective? i can provide more highlights that may help you resolve it holistically.

**Comment by VictoriaShyika** [comment]
@edenvidal  Yes, please show me that.

**Comment by edenvidal** [comment]
@VictoriaShyika 

https://github.com/rnbwdev/rnbw/assets/13418616/d772a325-9d26-4997-a5f1-ca6a2c32a8a5
