### ISSUE TITLE
Sometimes a single click also triggers the content editable property of a node or element.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#269]
A node/element on stageview becomes editable when it's double clicked, not on single click.

Issue: Node becomes content editable on single click.
Desired behaviour: It should become editable only on double click.

Reference: 

https://github.com/rnbwdev/rnbw/assets/38177419/fb25df66-5a6f-4344-91df-6301cf46ec78

Note: Start with identifying the cause of this issue. And then comment your approach to detecting and solving it.

**Comment by edenvidal** [comment]
the desired behavior is that a node should enter edit mode with a double click.
additionally, when a text node is in edit mode and another text node is selected, the newly selected text node should immediately enter edit mode.

**Comment by MadDog1994** [comment]
To avoid being able to edit the text on a single click, ensure that isEditing.current is always false in the onClick function. however, this logic is closely related to double-click, so I'll try to find a solution and solve it
