### ISSUE TITLE
Jumpstart

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#272]
- [x] bring back the description box
- [x] add "image" field for each item in the jumpstart.csv
- [x] @stanislavasal to create images for each menu item.
- [x] redirect "community" to github discussions in a new tab https://github.com/orgs/rnbwdev/discussions
- [x] redirect support to "mailto:hello@rnbw.company"

![Image](https://user-images.githubusercontent.com/13418616/256645535-bbee69c6-538a-415f-b695-5638a7705b8c.png)
![Image](https://user-images.githubusercontent.com/13418616/256645536-cff99b30-2fd4-44e6-86e9-30236595bab0.png)

**Comment by atulbhatt-system32** [comment]
@edenvidal few queries regarding this task.

-Bringing back the description, means adding a section on the right of the jumpstart menu that shows the description (start a new project) which comes from the jumpstart.csv

- What will come in the image field of jumpstart.csv? Url or image or path from the image stored locally or just the name of the image.

- Where are we going to show the image?

**Comment by edenvidal** [comment]
@atulbhatt-system32 
- right
- url of the image
- we're going to show the above the label. ("start a new project", then the image)

**Comment by stanislavasal** [comment]
@edenvidal @atulbhatt-system32 Hello! Excuse me, I have so many questions today... Could you please elaborate a bit more on which images we'll be adding and what description needs to be provided? I've read the messages above, but I'm still not entirely clear 😓

**Comment by atulbhatt-system32** [comment]
@stanislavasal there are various actions in Jumpstart menu. Like New, open. On the left side we have various actions that we can do and on right side we show description of the action that we hover on.

Above the description we will show some image that represents the action.

I guess that is what needs to be done.
Those images are required to be designed.

Am I right @edenvidal ?

**Comment by edenvidal** [comment]
yes. we can skip this one for now. i can provide more clear design
requirements soon

Eden Vidal <https://edenvidal.com>
Under <https://weareunder.design>

**Comment by edenvidal** [comment]
yes! @stanislavasal , this task include both code and design. i think it would be better to actually start with code, with a placeholder image, and then we can design the icons for each. wdyt?

**Comment by stanislavasal** [comment]
@edenvidal So, as far as I understand, first I need to write the code that will allow switching to different images when hovering over different buttons, using placeholder images. And then design the cards and replace them.

**Comment by edenvidal** [comment]
1. design the illustration for each item (160/160px) - this is the first task. we're starting with design. for each item, we're making a meaningful illustration. before we go on the next step, there an illustration for each item.
2. prepare the svg files by flattening a copy (not the master, a copy) of them and export them as a flat svg layer.
3. we use a command menu react component called "cmdk" it has a feature for displaying the preview/card alongside the menu item. find our with @Atul Bhatt how to work with it

**Comment by atulbhatt-system32** [comment]
@stanislavasal 

The image below shows the example.

- Go to https://cmdk.paco.me/
- Select Framer example to see how to create something similar
- Implement the same in rnbw with accordance to our design

![Image](https://github.com/rnbwdev/rnbw/assets/38177419/09f163bc-7a10-42d0-a9a1-b469a18d6aac)

**Comment by edenvidal** [comment]
@stanislavasal can you make a pr for that? we'll confirm and continue working on it

**Comment by edenvidal** [comment]
@atulbhatt-system32 can you confirm the pr (and we'll then close it)
