### ISSUE TITLE
Pasting text into stage

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#273]
#### in design mode (stage)

- [x] #494

- [x] #563

- [x] #564

- [x] #567

#### in code mode:
- [x] paste text as is, plain or html.

**Comment by atulbhatt-system32** [comment]
If we paste plain text as text, it creates a text node without any tag but currently, we don't have any representation of those nodes in our nodeTree.

We need to talk about this and finalize its implementation.

Shall we allow a plain text node or just put the text in a plain <span> tag?

**Comment by atulbhatt-system32** [comment]
For issue 3:

We have to see if we can get formatting information inside the copy event of the clipboard.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika you can work on part2 of this issue

**Comment by atulbhatt-system32** [comment]
@edenvidal ` if text is pasted not in text editing context but in a selected element context, consider this outcome the same as for when it text editing mode.`

Would love to get more details on this.

So if a text is pasted in when a node is selected but not in content-editable mode how shall we proceed the pasting operation.

**Comment by edenvidal** [comment]
there are two types of text pasting
- cmd+shift+v - unformatted text. in this case, the pasted text will be inside a `<span>` element.
- cmd+v - formatted (or unformatted) text - in this case, the pasted text will organize itself into 'formatting' type of elements (elements stated in rfrncs as such).

**Comment by atulbhatt-system32** [comment]
ok @edenvidal but in case the formatting is applied via attribute we won't be able to know how to keep it formatted. If it were plain simple formatting using tags like <b>,<strong>, <i>,etc then it were possible to have formatting.

**Comment by edenvidal** [comment]
@atulbhatt-system32 the rules i mentioned are in the context of tags like `<b>,<strong>, <i>`,etc. we should ignore attributes if any.

**Comment by atulbhatt-system32** [comment]
@edenvidal would be great to have some more explanation of the fourth checkbox/issue.

**Comment by edenvidal** [comment]
@atulbhatt-system32 make it clear

**Comment by edenvidal** [comment]
@edenvidal is "initialize editing mode for the newly created text" impossible
