### ISSUE TITLE
live local files sync

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#275]
goal - complete files sync. to enable quick re-rendering when files are changed/added, even by another application.
- [ ] sync optimization and persistence.
- [ ] complete correlation with active local dependencies (for example, fonts, images, js files)
- [ ] when autosave is on.

---

https://web.dev/origin-private-file-system/

**Comment by atulbhatt-system32** [comment]
More content related to files on the web:

https://web.dev/case-studies/kiwix?hl=en

https://web.dev/case-studies/kiwix?hl=en#how_the_opfs_works

https://web.dev/case-studies/kiwix?hl=en#implementing_a_mini_file_manager_in-app

**Comment by atulbhatt-system32** [comment]
There is no mechanism to get any event emitter we can hook to detect if a file is changed outside of rnbw.

For this, we have decided to follow another approach.

Here we assume that whenever the user focuses on the browser in which rnbw is opened, the user won't be making any changes from the local.

The interval in which the focus of the browser is lost and then again it is focused back is the time we assume there are chances for any changes that were made on the filesystem from the local.

Based on this we sync the file tree when the user focuses back.
