### ISSUE TITLE
Stage - "canvas" mode / zoom-in-out

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#278]
the ability to initiate 'zoom mode' within the stage context.
by default, it is 100% viewport, and the scroll behavior is coherent with the page. (which is the existing behavior)
when zooming in/out, the zoom-mode starts and the scroll (x/y) is within a 'canvas' context.

keyboard shortcuts 1-0
1-10% zoom
9-90% zoom
0-100% zoom.
150 - 150%
ESC - back to site mode (cancels canvas mode

-

extra:
shortcuts + / - 
25% more/less. defaults to it's closest 25 count pattern. 25/50/75/100/...

**Comment by edenvidal** [comment]
@MadDog1994
1. with the help of the "+" key, we can go to a zoom that is more than 100% and not limit it in any way.
2. in viewport mode - when resizing the browser, the stage reacts.
3. i zoom mode - when resizing the browser, it does not affect the stage, since it is controlled by the 'zoom'.
4. another issue is the outline for selected elements. when zooming in-out, it is growing. but we should always keep it the same thickness (1px). i don't know how we'll do that (😄)

**Comment by atulbhatt-system32** [comment]
@edenvidal how are we going to trigger 150%, we don't have a key to assign that zoom level

**Comment by edenvidal** [comment]
@atulbhatt-system32 it could be that this mechanism needs to be rethought in the broader context of some sort of canvas.

**Comment by edenvidal** [comment]
https://jsoncanvas.org/ wow

**Comment by atulbhatt-system32** [comment]
@edenvidal this is some good finding. I will think of how we can make the use of it in stage.
