### ISSUE TITLE
files renaming

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#280]

**Comment by atulbhatt-system32** [comment]
@edenvidal Would you please fill in more context to it.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika I think renaming is actually turn it into!

**Comment by VictoriaShyika** [comment]
@atulbhatt-system32 
Turn into for nodes is already added to the command panel, do I need to change the name to "rename", or change something else?

**Comment by edenvidal** [comment]
"turn into" is entirely different from "rename". i'll provide more information soon but you can ignore this for now.

**Comment by edenvidal** [comment]
so, this issue is specifically about handling 'renaming' of files and nodes.

- no need for a shortcut for it.
- for files - renaming the files
- for nodes - adding/changing a node's "id" attribute.

**Comment by atulbhatt-system32** [comment]
oh I totally was out of my mind that day I guess when I mixed it up with turn into nodes. It's for Files.
