### ISSUE TITLE
make history management aware of changes in the code and consider them as events

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#281]
HMS or History management System is responsible for saving the history of **events** in rnbw.

We have three important components in rnbw.
 - NodeTree
 - Stage
 - Codeview (Editor)
 
 Now, we can have history for all of them individually or a single history for all.
 
 Code editor tracks everything as a string and can have its own history as string.
 NodeTree can have its own and same for the stage.
 
 As in rnbw NodeTree, Stage and Codeview are always synced, we decided to have a global history management of rnbw as a whole.
 
We store the entire tree as a history object. The tree has all the data and information to revert back to the previous state of rnbw.

Even when we change any text in the codeview (editor) it changes the tree (node tree) which we store in our history.

## What are events in rnbw?
An event is any action that leads to change in the state of rainbow. Following are what we can consider as an event:

**On Stage:**
- Changing the focused node by clicking on an element.
- Editing an existing element.
- Adding a new element on the stage
- Deleting an element
- Cut, copy, paste as an individual action

**On Node Tree:**
- Focusing on a node
- Changing the order of a node
- Deleting a node

**On Codeview:** 
- Any change in the code content by typing, cut, copy, paste

@edenvidal you can add more thoughts on what more events we can add or refine this.
@jasonliu7040

Preserving the history:

The history will be unique for each file instance. If you opened a file then it's history starts recording. And when you switch to the other file the history gets cleared and rnbw start recording the history of new file. Even reload will clear the history.

@jasonliu7040 you can think of most of the events if not every will cause changes in the codeview, you can use this as a reference to how we should proceed with it.

- [x] #361  
- [x] #362 
- [x] #390

**Comment by atulbhatt-system32** [comment]
HMS or History management System is responsible for saving the history of events in rnbw.

We have three important components in rnbw.
 - NodeTree
 - Stage
 - Codeview (Editor)
 
 Now, we can have history for all of them individually or a single history for all.
 
 Code editor tracks everything as a string and can have its own history as string.
 NodeTree can have its own and same for the stage.
 
 As in rnbw NodeTree, Stage and Codeview are always synced, we decided to have a global history management of rnbw as a whole.
 
We store the entire tree as a history object. The tree has all the data and information to revert back to the previous state of rnbw.

Even when we change any text in the codeview (editor) it changes the tree (node tree) which we store in our history.

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
now it records the expand/collapse state of node tree as history events
also for file tree.
what do you think? we should keep/ignore them?

**Comment by atulbhatt-system32** [comment]
> Member

Let's see the behavior of nodes in figma as well as vscode. And then decide. You can give your feedback here.

**Comment by jasonliu7040** [comment]
at both of vscode and figma, they don't keep the expand/collapse status of the nodes as events.
so let's not keep them as events too.
it would be enough if we expand the nodes-line to focused item from root node, so that the users can see it in the tree view.
wdyt?

**Comment by atulbhatt-system32** [comment]
Yeah, that sounds good.
