### ISSUE TITLE
when using the "delete file" function, the homepage should become selected if available, similar to the initial function.

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#282]

**Comment by atulbhatt-system32** [comment]
@edenvidal need more detail or context for it

**Comment by jasonliu7040** [comment]
@edenvidal @atulbhatt-system32 
is this the issues for the case of deleting currently opened file?

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 it's not an issue,  it's an edge case handling. I also need clarity on this what do we mean by homepage, is it index.html?

**Comment by edenvidal** [comment]
@atulbhatt-system32 , @jasonliu7040 - The project should default to index.html if it exists. There is already a handler to do this when starting a project. The function for deleting a page should be linked to this handler.

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 , @jasonliu7040 - The project should default to index.html if it exists. There is already a handler to do this when starting a project. The function for deleting a page should be linked to this handler.

oh ok @edenvidal got it.

**Comment by jasonliu7040** [comment]
@edenvidal @atulbhatt-system32 
I already implemented that in `reloadProject` progress.

![image](https://github.com/rnbwdev/rnbw/assets/146990379/f84ee4a7-4893-4ec6-b9fc-1a80f3e480d1)

**Comment by atulbhatt-system32** [comment]
yeah it's there. This ticket can be closed
