### ISSUE TITLE
StageView update using morph-dom

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#312]
The purpose of this issues is as follows:

- Identifying what all should be covered for a proper stage view implementation.
- Is it possible to do stage view update using dom-diffing library morph-dom.
- If it's possible to achieve that, implement stageview sync and all stageview features with the help of morph-dom

Here are some issues related to it:

- [x] #315
- [x] #316
- [x] #317
- [x] #319
- [x] #320
- [x] #324
- [x] #325
- [x] #331
- [x] #334
- [x] #340

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika  you can start with first point and describe all of it here, after properly identifying it. You can refer to rnbw.dev for how it works or what all we do.

And apart from that there are other things which we want to achieve in this.
For ex: #273

And other apis too: like add a new node, delete a selected node, copy a selected node, and you can list what all comes to your mind and we will together validate it.

**Comment by VictoriaShyika** [comment]
What should be covered for a proper stage view implementation:

a. Action from nodeTree:
- Add a new node;
- Delete a node;
- Duplicate node;
- Copy node;
- Cut node;
- Paste node;
- Drag and drop;
(Need to update position of node in NodeTree after each node action)

- Group and Ungroup nodes;
(Need to add or delete group container)

- Multiple selection;
(Need to highlight selected node in NodeTree and in stage)

b. Action from stage:
- Editing existing stage text;
- Deleting node by pressing delete in selected element context;
- Paste plain text as text;

- Paste text that is html and turn it into nodes;
(Need to check if pasted text is html)

- Paste text that has special formatting and preserve the formatting by converting it into corresponding nodes;
(Use RegEx or other tools for check if pasted text has special formatting)

- Paste text even if text is pasted in a selected element context;

**Comment by atulbhatt-system32** [comment]
I think nodetree is more or less part of stage when it comes to performing actions.

Let's breakdown the process into groups with similar functionalities and try to prioritize their execution. The result of actions should reflect on both the stage and the nodeTree.

**Basic Ones:**

- [ ] Single Selection of Node (highlight)
- [ ] Multiple Selection of Nodes
- [ ] Grouping of Nodes

Let's start with verifying there functionality if it works correctyl.

**Node Actions:** 

These actions require only the source node id.

- [ ] Delete a single / multiple nodes. We will have ids of the selected nodes and based on that we can remove the code of those nodes from our codeview, parse it and then provide morph-dom with the new htmlInApp and current htmlInApp and let it update the stageview.

- [ ] Duplication of a node (question: can we duplicate multiple nodes? How this happens in figma). Let's say for single node we can duplicate. When we duplicate a node it means we insert a copy of it below it. This essentially means we copy the node in monaco (based on start and endIndex or particular node code location) and insert it (paste it | append) just after the endIndex of the selected node. Then we follow same process of parsing and morph-dom.

You can try to check these implementations meanwhile @VictoriaShyika and implement them.

**Comment by atulbhatt-system32** [comment]
Also @VictoriaShyika you can check how I implemented the stageview contenteditable part

**Comment by atulbhatt-system32** [comment]
Here are some findings by @VictoriaShyika and @atulbhatt-system32 

- [ ] Selection of single node works correctly.
- [ ] Deletion of nodes is happening when pressing `backspace` key but not with `Delete` key.
- [ ] Multiple Selection is only happening through nodes, but it should also happen for stage view also.
- [ ] Deletion of node results in incorrect nodes position in codeview.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika 
What does this mean?
Paste text even if text is pasted in a selected element context.

Does this mean that we can copy the text inside a node even if it's not in content-editable mode?

Currently we can paste any text, if a node is selected. It pastes it similar to how we do it when we copy a node.

But the issue with that is it isn't wrap inside any element. We will have to add a check for it.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika 

For `Paste text that has special formatting and preserve the formatting by converting it into corresponding nodes;`

we don't get any formatting information when we paste it. So I don't know how we can achieve that.
