### ISSUE TITLE
Deletion of nodes is happening when pressing `backspace` key but not with `Delete` key.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#315]

**Comment by atulbhatt-system32** [comment]
@edenvidal currently the way our Actions.csv is there it won't allow us to have multiple keys to perform same actions.

@jasonliu7040 what are your thoughts on it!

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 , what you want is to keep  both of "Delete and Backspace" as delete-node-action?

**Comment by atulbhatt-system32** [comment]
Yeah I mean changing to delete is easy, but for this specific issue or requirement I would like to have it work using both.

If not delete is the preferred that can be eaaily changed.

**Comment by edenvidal** [comment]
@atulbhatt-system32 we can decide that we fill the data of keys as an array with ',' separation or something and create a behavior that interprets it as such.

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 we can decide that we fill the data of keys as an array with ',' separation or something and create a behavior that interprets it as such.

Yeah @edenvidal I also thought of the same thing.
