### ISSUE TITLE
actionsPanel and codeView show/hide

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#363]
need to be sure how it should work for actionsPanel & codeView visibility.

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 , please let me know regarding the above logic for now, thx.

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 we have codeview toggle.

When a file is open we keep it open.

To hide actionPanel also we have a shortcut.

**Comment by atulbhatt-system32** [comment]
Can you be more precise with your question?

**Comment by edenvidal** [comment]
i need more info about this issue/task @atulbhatt-system32 @jasonliu7040

**Comment by jasonliu7040** [comment]
@edenvidal , so now we have cmdk shortcuts to show/hide actionspanel and codeview.
of course that works.
but I am asking for the cases that show/hide them automatically.

- when we visit rnwb.dev, it first shows Jumpstart and actionspanel and codeview are hidden.
- when we close the Jumpstart or open a new project, it shows them.

is it just that? or do we have any other cases? is it clear for you?

**Comment by edenvidal** [comment]
@jasonliu7040 got it. so the shortcuts stay the same, but the automatic behavior is no longer relevant since we will revert to stacked panels (see https://guide.rnbw.dev/quick-start). so, both the sidebar+code are shown by default in the initial state.

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 do you have more questions on it or we can close this.

**Comment by jasonliu7040** [comment]
no question, am closing it now.
