### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#365]
- [ ] codeView has some css issue.

we have scroll cause of its incorrect height.

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/04799395-2efc-4447-8e39-111781af6cf3)

**Comment by edenvidal** [comment]
@jasonliu7040 @atulbhatt-system32 i think this is also no longer relevant as we're reverting to stacked [panels](https://github.com/orgs/rnbwdev/projects/4/views/5?pane=issue&itemId=34719358)
