### ISSUE TITLE
redefine processor workflow

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#376]
we can have only "from" in "updateOptions" state.
need to think more about it.

here's the diagram we need to complete
https://expl.ai/YNPBSCKC

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 how can I help?

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
now for history management, I am using currentFileContent.
as you know, it's not contentInApp but just would be real file content.

so in the case, we need to how to record the Group/UnGroup node events.
I remember that you said we will implement those events as code changes, right?
but maybe that code change would be happen in contentInApp, not for currentFileContent.
you see what I mean?
pls share your thoughts.

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 
> now for history management, I am using currentFileContent.
> as you know, it's not contentInApp but just would be real file content.
> 
> so in the case, we need to how to record the Group/UnGroup node events.
> I remember that you said we will implement those events as code changes, right?
> but maybe that code change would be happen in contentInApp, not for currentFileContent.
> you see what I mean?
> pls share your thoughts.

Group and Ungroup changes the content too not just contentInApp.

Except node events like select, multi-select, etc  the code content changes.

Can you give me any example where it doesn't!

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
if so, no problem.
I just thought group/ungroup will change contentInApp. no problem then.

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 
> if so, no problem.
> I just thought group/ungroup will change contentInApp. no problem then.

It will change both.

**Comment by jasonliu7040** [comment]
I see. just curious.. :)
do we have already code for that in the project. I just want to see how we are fixing that.

**Comment by atulbhatt-system32** [comment]
> I see. just curious.. :)
> do we have already code for that in the project. I just want to see how we are fixing that.

Yeah do multi-select and press ctrl+j I guess for it.

And you can do a global search for "group"

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 do we still have any open questions for this or we can close it?
