### ISSUE TITLE
set timer for file tree reload

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#384]
it needs to detect file system changes and make side effects to file tree view.
can fix that using timer with reloadProject API.

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 is it to detect filesytem changes done outside of the rnbw?

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
it's mainly for file-system changes outside of the rnbw, but I think we can also use it for in-rnbw filesystem changes.
for example, if you do any file-actions, you won't need to make any side-effects to file-tree. wdyt?

**Comment by atulbhatt-system32** [comment]
Hoe much expensive is this filetree reload process?

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
it is a bit complicated process.
what we need now is not to set timer.
it would be enough to complete "reload-project" process, since we can set "realod" button or timer later.

**Comment by atulbhatt-system32** [comment]
yeah! let's wait to jump on this ticket with proper research to do it in a proper way

**Comment by edenvidal** [comment]
@atulbhatt-system32 , @jasonliu7040 is it related to "files-sync"

**Comment by atulbhatt-system32** [comment]
Yes @edenvidal 

There is no mechanism to get any event emitter we can hook to detect if a file is changed outside of rnbw.

For this, we have decided to follow another approach.

Here we assume that whenever the user focuses on the browser in which rnbw is opened, the user won't be making any changes from the local.

The interval in which the focus of the browser is lost and then again it is focused back is the time we assume there are chances for any changes that were made on the filesystem from the local.

Based on this we sync the file tree when the user focuses back.

**Comment by edenvidal** [comment]
@atulbhatt-system32 this approach seems legit. would love to test and see how it works 🙌

**Comment by atulbhatt-system32** [comment]
sure @edenvidal definitely will update you whenever it's completed

**Comment by atulbhatt-system32** [comment]
closing because we are addressing it in a different ticket. This ticket's purpose was to propose a solution which we did.
