### ISSUE TITLE
complete api body for node actions.

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#386]
we have `/_node/node/actions.ts` which has node-action-apis called in `callNodeApi`

- [x] add
- [x] remove
- [x] cut
- [x] copy
- [x] paste
- [x] duplicate
- [x] move
- [ ] #409
- [x] #408
- [x] ungroup

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
I will take `remove` and `duplicate`
can you take `copy` and `move` please?

**Comment by atulbhatt-system32** [comment]
Okay sure @jasonliu7040
