### ISSUE TITLE
keep stageview node select status as an event

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#390]
make it work as the node tree.
just need to call `setSelectedNodeUids` when you call `selectNodeTreeNodes` for stage-view node-select events.

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/2002ed1e-f545-469c-b11b-73779b16fcc4)

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 seems like this is working!
