### ISSUE TITLE
node tree DnD works weird

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#417]
seems it work well for the first time.
but if you continue to do, the code in monaco-editor changes weird.

- [x]  when we select any node, we should see it in node-tree as expanded one.
- [x] pastCode error
- [x] error
![Image](https://github.com/rnbwdev/rnbw/assets/92056073/cf3a7e11-7f52-437c-8227-c0ee99e299ab)

**Comment by VictoriaShyika** [comment]
@jasonliu7040  I created new branch from dev for that

**Comment by jasonliu7040** [comment]
@VictoriaShyika 
I mean how are you gonna fix that? since I want to be sure which component you are gonna fix.

**Comment by VictoriaShyika** [comment]
@jasonliu7040 
For expanding issue I mean that when we drag node on element and element expands (if element was not expanded) we cant select expanded nodes, maybe its become of memoization. I not sure where we should make changes but maybe useNodeTreeEvent good for it, what do you think?

**Comment by jasonliu7040** [comment]
@VictoriaShyika 
ah I see your point. so you mean expanding the nodes while dragging. okay that's also the one we should implement.
got it.
I think we should fix that in `NodeTreeView.tsx` 
you know, we already have hooks for them.

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/b997c20b-7b2d-497c-bf2a-85f9490795dd)

**Comment by jasonliu7040** [comment]
so in `hoveredNodeUid-useEffect`, we can expand the nodes if it's dragging.
but in the case, we should set some delay when hovering, you see what I mean? so while dragging, when you hovering nodes for some time, that node will be expanded.

and in `focusedItem-useEffect`, we can expand the nodes.

**Comment by VictoriaShyika** [comment]
now delay for expanding is located in onDragEnter, we should move it to the hover hook?

**Comment by jasonliu7040** [comment]
@VictoriaShyika that's your choice. you can take which you think it's the best. cause I am not sure how it works now. :)
but sure thing is that we should implement that in `NodeTreeView`, not in `Processor`.

**Comment by VictoriaShyika** [comment]
Yes, I agree with you

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika it is expanding all the nodes, right now.
