### ISSUE TITLE
undo/redo(especially redo) is not working sometimes for file content change(node actions & code view edit)

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#428]
undo/redo works well for node select status, but not work sometimes with `node actions & code edit in code-view` that changes file content.
need to check and see the reason.

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
through checking, I think this maybe the reason.
just calling `handleEditorChange` in the `Processor` caused it.
I can see that some reducer actions are called incorrectly in `handleEditorChange`.

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/fbbd5e65-9911-45fc-8b63-20253d4ea528)

as the solution, I think we should move `handleEditorChange` code into `Processor` by reviewing & optimizing it.
please share your thoughts.

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 
> through checking, I think this maybe the reason.
> just calling `handleEditorChange` in the `Processor` caused it.
> I can see that some reducer actions are called incorrectly in `handleEditorChange`.
> 
> ![Image](https://github.com/rnbwdev/rnbw/assets/146990379/fbbd5e65-9911-45fc-8b63-20253d4ea528)
> 
> as the solution, I think we should move `handleEditorChange` code into `Processor` by reviewing & optimizing it.
> please share your thoughts.

@jasonliu7040 If it's possible can you take on this task. As this is important. And if you feel you need any information on it I can help you with it.

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
sure, I will fix that. and will ask you if I have any questions for dom-diff.
