### ISSUE TITLE
tagname is not correct in NodeTree after some node actions are performed like add, group/ungroup, etc

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#434]
when you do group/ungroup, the node tree `displayName` doesn't match the code view.
and stage view focused node is not synced with node tree.

- when do group

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/05420ba3-2134-4d76-a794-4a2d4fb1e849)

- when do ungroup

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/6ad54cbd-f861-44e4-bec9-273c60b1cbd5)

- when add

https://github.com/rnbwdev/rnbw/assets/146990379/cc24267c-d48b-4991-af48-ea0396bf4860

**Comment by atulbhatt-system32** [comment]
I have nailed down the origin of the issue and to some extent the cause of the issue. Solving it raises another issue as depicted in the video below:


https://github.com/rnbwdev/rnbw/assets/38177419/57f70ce6-6e3a-4f78-aa6b-4ad41696efb8

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika this issue is related to useMemo for getting name from htmlReference in NodeTreeView
