### ISSUE TITLE
automatically selected node is not synced at the first time

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#442]
- [x] code view #458 
- [x] stage view #459 

seems it(first element inside the `body` element) is automatically selected at the first time(when you open the project).
but it's only selected in node-tree, but not in stage-view or code-view.
need to sync them.

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/c663b321-830d-4850-8176-792a94556021)

**Comment by edenvidal** [comment]
yes. it's an "initial" rule that follows an ongoing one.
