### ISSUE TITLE
"Add" doesn't work correctly.

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#448]
it works first time.
but after that, always the same element ( first time added element ) is added.

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 I wasn't able to reproduce it. Can you share some video of it!

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 

https://github.com/rnbwdev/rnbw/assets/146990379/cc24267c-d48b-4991-af48-ea0396bf4860

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 this issue seems to be related to #434
