### ISSUE TITLE
use of `selectedNodeUids`

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#457]
we have updates for node-select-status syncing way.

all of node select status (expand, focus, select) must come from `selectedNodeUids`
- it's an array of node uids.
- it will be selectedItems of node-tree.
- the last element would be focusedItem of node-tree.

once focusedItem is updated, we should expand to it or do other side effects.

**Comment by atulbhatt-system32** [comment]
Yeah! I align with it. We can remove all the other stuff. It will be easy to track.

Right now we have a separate state for focus, which as mentioned we can always derive from the last item in selectedNodeUids.
