### ISSUE TITLE
codeView refactor

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#458]
should remove unnecessary code and optimize its component structure.

- useEditorWrapper.tsx
do we need this?

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/799ae9b6-fdcf-4f29-89fd-a4ec8e3343bd)

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 this I am not sure.

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
okay, no worries. I already removed that.
