### ISSUE TITLE
stageView refactor

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#459]
should remove unnecessary code and optimize its component structure.

- why don't we use "dblclick" event instead of this?
![image](https://github.com/rnbwdev/rnbw/assets/146990379/f18c50e9-5dbd-4e33-a10f-27e23f3173f7)

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 maybe double click wasn't giving the pointerevents but mouseevents
