### ISSUE TITLE
complete Content-Editable feature

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#472]
- [x] #470
- [x] #468

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
so when we dbl-click on stage-view element and edit text, it should be synced with code-view, even if we don't press Escape or clicking other element?
see what I mean?

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
and what about dbl-clicking on WebComponent?

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 so when we dbl-click on stage-view element and edit text, it should be synced with code-view, even if we don't press Escape or clicking other element? see what I mean?

So when we exit content-editable mode we should which is by pressing "esc" or clicking anywhere else other than the editable node or element we should sync the cahnges

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 and what about dbl-clicking on WebComponent? what should we do in the case?

We will create a separate ticket for it but ideally it should open the file related to it.
