### ISSUE TITLE
if copied text is html, automatically turn it into nodes.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#494]

**Comment by edenvidal** [comment]
@atulbhatt-system32 @VictoriaShyika, it works nice. how does it work? do we have a "pasting mechanism" that detects html patterns? thanks.

**Comment by atulbhatt-system32** [comment]
@edenvidal we no longer follow the approach of using regex to find patterns for an HTML. 
We pass the string to the parser and it does that magic. It simply turns the string into HTML nodes.
