### ISSUE TITLE
web component works weird for node actions.

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#503]
just checked with `Copy` & `Paste` on a web component.
but it works weird. now sure what the reason is and also what more issues we have.
need to check and find out the reason of the weird bugs.

here's an attachment.

https://github.com/rnbwdev/rnbw/assets/146990379/442adf98-cdbe-4ee4-8d4a-1ecd8603767c

**Comment by edenvidal** [comment]
@atulbhatt-system32 @jasonliu7040 is this relevant?

**Comment by jasonliu7040** [comment]
@edenvidal This error comes from morphdom. #602 is related to morphdom as well.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika you just need to identify what exactly is happening that's causing the issue. Not resolve it.

**Comment by edenvidal** [comment]
@atulbhatt-system32 is this task relevant? if not. let's close it. if relevant, let's put the information in the web component issue. 🙏
