### ISSUE TITLE
`sourceCodeLocation` is incorrect when the node has no `endTag`

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#512]
### how to reproduce.
just add any html tag without `endTag` in code-view.
eg: <p>paragraph

and then try to undo/redo.
you can see highlighted code is incorrect. need to fix that.

![Image](https://github.com/rnbwdev/rnbw/assets/146990379/8af787e1-6811-457a-8c14-ddb23a9d79d0)

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 , please let me know what you think for the correct approach. thanks

**Comment by atulbhatt-system32** [comment]
@jasonliu7040 I think we can let it this way itself where it selects the blank spaces until the end tag is not found or some other tag is not encountered.

As the code is not correct we can't do much about it.
