### ISSUE TITLE
NavigatorPanel UX/UI

### ISSUE THREAD

**Issue by jasonliu7040** [rnbwdev/rnbw#516]
It provides inconvenience and also has some ui glitches.
need to improve it while fixing file-system issues.
so that we can test everything easily.

Other subtasks that may belong to this.
- [ ] better and more accurate drag and drop.
  - it seems that the tree view's library enables a more specific one.
- [ ] remove the clipped nodes.

**Comment by jasonliu7040** [comment]
@VictoriaShyika I think you worked on this part already.
so can you improve it and give me some description please? I will appreciate it.

**Comment by jasonliu7040** [comment]
@atulbhatt-system32 
please share me with your ideal approaches. thanks.

**Comment by atulbhatt-system32** [comment]
Closing as addressing the same in #373
