### ISSUE TITLE
html (web) components - stage handler

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#547]
- [x] Open up (and select on the files panel) the locally referenced js file. if external - it is doing nothing.
- [ ] The code panel when the JS file is opened should not interfere (such as scroll) with the HTML node
- [ ] The code panel shouldn't start from the end when opening wc file.
- [ ] The file panel shouldn't get collapsed and the node panel shouldn't expand

**Comment by edenvidal** [comment]
@atulbhatt-system32 

- [ ] while it is true that the file manager and code view should reflect the opening of the js file, the currently active page should stay active on stage.
- [ ] When clicking somewhere on stage. the file manager + code view should then reflect the currently active page again.

consdier the web component stage handler as a quick sub-context switching, but then you should be able to quickly get back to the main context.

**Comment by atulbhatt-system32** [comment]
@edenvidal sure

**Comment by edenvidal** [comment]
@atulbhatt-system32 it works great. only thing is that the url didn't change to reflect the currently open js file. was still pointing at http://localhost:8080/#/under/index.html. wdyt? could be actually ok to continue representing the open page in this case.

**Comment by atulbhatt-system32** [comment]
It was tricky to have stage with different files showing and the codeview to have different files opened (like a special condition) which was not covered in the routing task. So will have to make it work for that case too.

That case is missed, will match the path to the javascript file of the web component.

**Comment by edenvidal** [comment]
@atulbhatt-system32 if it is too painful for now, we can get back to it later.

**Comment by edenvidal** [comment]
@atulbhatt-system32 recorded on slack.

**Comment by edenvidal** [comment]
agree! (:
