### ISSUE TITLE
stacked and resizable panels

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#548]
- [x] open/close the sidebar using the `\` shortcut.
- [x] resizinge feature: adjust sidebar width by clicking and dragging its edge.
- [x] The codeview to be stacked on the right instead of bottom.
- [x] when hover to the left side or view port - sidebar slides-in (see notion)

**Comment by atulbhatt-system32** [comment]
@edenvidal  Currently, the shortcut for the sidebar is "\". Do we need to change it to "/"?

**Comment by edenvidal** [comment]
no @atulbhatt-system32 my bad (:

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika you can check https://phcode.dev/ for the implementation of stacked and resizable panels. However, in our case, the stage will be in the center. And codeview will be on the right.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika I think you are still missing the last point in your implementation.



![Image](https://github.com/rnbwdev/rnbw/assets/38177419/53e07cf4-465b-4d78-a84f-8463d6242dcf)

See this screenshot. There are 2 marks fields or icons. They both work in a similar fashion. One implementation is in Notion and other in the Arc browser for mac. You can refer to both of them. I prefer arc implementation better as it considers full height unlike in Notion where the height of the sidebar is not full.

So Arc is a better example.

**Comment by VictoriaShyika** [comment]
@atulbhatt-system32 but task related with hover to the left side, or do we need to add icon(button) that will show/hide the panel?

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika you can refer from here

https://svg-icon.xyz/
https://github.com/rnbwdev/raincons/tree/main/icons

and see if there is any suitable icon which we can use for now.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika added a new point. For it you can see even the vs code for the icon that we see for resize. And for highlight mechanism of the panel edge on hover you can use the same technique that I have deployed for loading bar.
