### ISSUE TITLE
add global progress bar

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#551]
a multipurpose progress bar that can handle situations
- [x] where the project being loaded is too heavy
- [x] when a specific page is still loading
- [x] when there are actions that take time to operate, or while dealing with too many nodes.
- [x] the bar isn't visible in light mode (white) since the stage's default color is white. i'm thinking, maybe we can have it always black and use `mix-blend-mode: difference;` ?
- [x] let's remove the box-shadow in there.

**Comment by edenvidal** [comment]
@VictoriaShyika i'm not sure what the current mechanics of the progress bar but i'd like to think about how we can make it work globally for whenever and whatever data is processed. example: [this site](https://github.com/weareunder/under) is pretty heavy with content. it takes some time to load it and i believe the progress bar gotta indicate that. wdyt?

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika I think the case here is to have loader even when the domContent is loading inside the iframe

**Comment by edenvidal** [comment]
@VictoriaShyika it works great. two issues related to its visiblity

- [ ] the bar isn't visible in light mode (white) since the stage's default color is white. i'm thinking, maybe we can have it always black and use `mix-blend-mode: difference;` ?
- [ ] let's remove the box-shadow in there.

**Comment by atulbhatt-system32** [comment]
@edenvidal I haven't used mix-blend-mode but a conditional background for the loading bar. This improves the visibility.
