### ISSUE TITLE
when loading a new project, nothing is loaded on the initial state - might be affected by the file deletion intervention

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#552]

**Comment by atulbhatt-system32** [comment]
@edenvidal seems it doesn't happen all the time. Steps to reproduce it would be helpful.

**Comment by edenvidal** [comment]
@atulbhatt-system32 true. i think once there's a fallback, it doesn't try to locate the index.html anymore. try to reproduce by opening a project without index.html and then with.

**Comment by atulbhatt-system32** [comment]
Sure @edenvidal will try it,

**Comment by atulbhatt-system32** [comment]
@edenvidal I tested this on `rnbw-guide` project with its index.html file deleted. Now I opened the project again it opened `404.html`
