### ISSUE TITLE
✨🌈 rnbw.design - developers guide 🌈 ✨

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#554]
the core idea is that there's a single, powerful api for `actions`.
this api is flexible and can be used to do anything you need - users can interact with this api through various hooks. these hooks allow users to modify behavior without touching the api itself.
users will even be able to create their own actions, essentially adding new functions as middleware.

- [x]  api / syntax list - api names, input, output, brief description of each call, etc. @atulbhatt-system32
- [x] combine and then remove [parts in here](https://www.notion.so/underdesign/developers-guide-480cf1fa76ac4877ac51624448d9997e?pvs=4) @atulbhatt-system32 
- [x]  Open guide for developers on how to create
  - [x] actions + example @atulbhatt-system32 
  - [x] contribute directly to rnbw core - short text referring to the repo's readme.md

**Comment by edenvidal** [comment]
https://www.notion.so/rnbw/docs-developers-95b1fe00141d492e9620dbdcd9ef3682?pvs=4

**Comment by edenvidal** [comment]
@atulbhatt-system32 moved back to "in progress". waiting for the editing [here](https://www.notion.so/underdesign/developers-guide-480cf1fa76ac4877ac51624448d9997e?pvs=4)..

**Comment by atulbhatt-system32** [comment]
@edenvidal I removed it from in progress because the ticket inside it is already in progress. If this is creating confusion so let's have it also in `in progress`

The package details will all be update in docs once this master this issue we have closed entirely.

**Comment by edenvidal** [comment]
@atulbhatt-system32 i've edited the checkboxes [here](https://github.com/rnbwdev/rnbw/issues/554#issue-2061539309) to bring focus.

**Comment by edenvidal** [comment]
@atulbhatt-system32 let's remove "Span Paste" as both exposed action in command menus and in API. users either do `cmd+v` or `cmd+shift+v` and then rnbw knows how to handle it. it is all just "Paste"
