### ISSUE TITLE
Stage Hover Indicator : hover on element (outline), hover on text (underline)

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#557]

**Comment by edenvidal** [comment]
@atulbhatt-system32 so, there are two issues with the implementation

- [ ] the 'active' state (outline) should not be affected. we're only talking about the hover state here.
- [ ] the hover on text (underline) should be a 1px bottom outline. and not the text's underline (:

**Comment by atulbhatt-system32** [comment]
@edenvidal understood I will check the figma

**Comment by edenvidal** [comment]
recored a short video on slack on how to make last tiny adjustments to it @atulbhatt-system32

**Comment by atulbhatt-system32** [comment]
@edenvidal this is updated I think now it needs one more last feedback

**Comment by edenvidal** [comment]
@atulbhatt-system32 so nice!!!
