### ISSUE TITLE
stage - single/multi-level depth navigation

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#558]
Figma allows you to navigate through single/multi-level depths by clicking on the elements in the canvas.

- [x] To navigate down through container elements, you can simply double-click on them.
- [x] Additionally, you can select multiple elements in all levels by holding the cmd key and clicking on them.
- [x] If you need to enable multiple multi-level selections, hold the shift and command keys while double-clicking on the elements.

1st Step
======
- [x] Text nodes are currently not visible, they should be visible.
Now, there may be some pure reasons for not showing them as "\n" and other unrequired nodes will hinder the use cause but we will look into them later, after reaching this point.

- [x]  Only text-nodes are content-editable (however, the challenge is are `#text` node really content-editable (I doubt that).

2nd Step
=======

- [x] Make the current functionality of to be able to select/hover on any nested element by pressing `cmd` while hovering and clicking similar to figma.
- [x] And create a new functionality to achieve what figma allows us to do is travel inside a node in depth by double clicking. Parent->childA
childA => child A.1
- [x] Releasing the cmd when hover should not persist the behaviour of pressing it. You can check figma for the same.
- [x] #747

3rd Step
=======
- [x] show #text node only when an element got other element as its children together with #text node
- [x] Improve validations to include operations on `#text` node copy, paste, DnD, etc

Note: please work with figma once to understand it better.

**Comment by VictoriaShyika** [comment]
@edenvidal 

1: Now in the application, selection takes place on a specific element, and not on its container, therefore, with the existing logic, it makes no sense to move down the elements of the container, because the deepest element is already selected. Unless there is an option to change the logic of selecting nodes from the scene, but in my opinion, this will only complicate the application.

2,3: The behavior as in 2 and 3 I cannot follow in the figma as it is described in the task, however, selection from the scene now works with Shift.

I need more information to complete this task.

**Comment by edenvidal** [comment]
@atulbhatt-system32 described.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika I've updated the description.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika as `#text` text nodes are not content-editable why not make them a `<span>` element in stage with some `attribute` to identify this span is `text` node. Wdyt?

**Comment by VictoriaShyika** [comment]
@atulbhatt-system32  What about nodeTree, in nodeTree should we also to change #text to `<span>`?

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika this is just for the purpose of enabling content editable for `#text` node. We never change the original code of user and hence nodeTree should reflect it as `#text` node.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika let's show `#text` node only when an element got other element as its children together with `#text` node. Wdyt?

**Comment by edenvidal** [comment]
i'm not sure why the "#text" thing is discussed, in here (let's divide it?) but anyway, here's my idea:
imagine text editing is a "mode", which is initiated when...
1. double clicking on a :formatting and text" element type (instead of the redundant 2xdouble clicks in order to edit text).
2. once already in this mode, it is possible to simply click on other text elements and edit them freely (see figma).
3. it is also possible to hit T on the keyboard and initiate that mode.
