### ISSUE TITLE
replace ⌘ with Ctrl for windows

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#560]
- [ ] replace `⌘` with `Ctrl` for windows

**Comment by atulbhatt-system32** [comment]
@edenvidal what do you mean by that? 
Is it like showing the icon based on that?

**Comment by edenvidal** [comment]
@atulbhatt-system32 exactly. i'll create a `ctrl` icon

**Comment by edenvidal** [comment]
@atulbhatt-system32 updated.

**Comment by edenvidal** [comment]
@atulbhatt-system32 question - as a (soon not anymore) window user, is it also reflected in the command menus? (:

**Comment by atulbhatt-system32** [comment]
As a widows user I can say yes it does.



![Image](https://github.com/rnbwdev/rnbw/assets/38177419/aa6d03dc-42e3-4043-9d61-4ac61e381899)
