### ISSUE TITLE
Enable formatted and unformatted text pasting.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#563]
There are two types of text pasting

- [x] cmd+shift+v - unformatted text. in this case, the pasted text will be inside a `<span>` element.
- [x] cmd+v - formatted (or unformatted) text - in this case, the pasted text will be inside a `<p>` element. and the context inside will organize itself. the allowed elements are 'formatting' elements (elements stated in rfrncs as such).

**Comment by edenvidal** [comment]
@atulbhatt-system32 i made the second one clear. use case - I am copying a formatted text from notion or my email that includes bullet points, numbers, and some bold or italic markings. Then I pasted it inside rainbow, so I expect to have the same way, but as HTML elements.

**Comment by atulbhatt-system32** [comment]
@edenvidal But the point is that I how do I decide based on their custom styling they apply to achieve the bold, h1, h2 effects without using those exact tags?

Suppose they used:

<p style="font-size:56px; font-weight: bold;">This is Heading1</p>

In this case it may look like heading1 but it's not.

Otherwise, if you provide it the same thing in this way.

<h1> Heading 1</h1> It should already be wroking

**Comment by edenvidal** [comment]
aha, i see your point. the question is, how do we handle styled elements? I think that by default, we should only handle markup and ignore the 'style' attr in elements.

and yes, it is working but ignoring markup. try to copy and paste from notion. also, the pasted text should be inside a <p> element (:

**Comment by atulbhatt-system32** [comment]
@edenvidal so when we copy via ctrl+v we will allow the attribute to correct!
Yeah I will add it inside `<p>` or shall I do it inside a `<div>` as the pasted content can contain even a div. As div can contain anything won't it be better to have the wrapper as `div`

**Comment by edenvidal** [comment]
i see your point here too @atulbhatt-system32 . yes, when we paste with cmd+v, we only allow markup (elements).

and yes, let's go with `<div>`. i guess we'll have to test actual usage and return to it wiser.

**Comment by atulbhatt-system32** [comment]
ok so only thing left is to wrap in div if we are only allowing markup

**Comment by atulbhatt-system32** [comment]
@edenvidal this can be tested
