### ISSUE TITLE
The new element created by pasting text should be in content-editable mode.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#567]

**Comment by atulbhatt-system32** [comment]
So as much as a straightforward task, it feels like it isn't.
The major challenge here is that we have to identify if a node is focused after performing a paste operation and then we have to make it content-editable.

But we run side effects for all the events and then after the change is done we identify the node that is required to be focused.

**Comment by edenvidal** [comment]
@atulbhatt-system32 i see your point. let's ignore this for now and get back to this improvement if it makes sense in a greater context.
