### ISSUE TITLE
Make Formatting (prettier) an optional setting in Jumpstart that can be toggled

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#577]
I've made some changes and then went back in history to the initial state, and something in the original has changed.

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/c167435e-a246-4b5b-a88d-a92aa2ccfb57)

**Comment by edenvidal** [comment]
@atulbhatt-system32 got it. good idea

**Comment by atulbhatt-system32** [comment]
@edenvidal this is also implemented

**Comment by edenvidal** [comment]
@atulbhatt-system32 awesome. i like it that we called it "Format Code" which is more generic and precise and not "prettifier" 😄
