### ISSUE TITLE
Incorrect code gets selected in codeview after contenteditable is edited and undoed

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#588]
- [x] Currently the when we confirm the content of content-editable by focusing on another element then those 2 events are considered 2 different one. So the issue with this is that when we try to undo it, first the element content gets undo and then another undo leads to its selection. This is an incorrect behaviour.

https://github.com/rnbwdev/rnbw/assets/38177419/aa5a9849-9270-4fca-9fb4-716e80354228

The issue is back again.
Here is the glimpse of it.

**Comment by edenvidal** [comment]
@atulbhatt-system32 after editing text, and clicking on another element. there's no focus indication on the selected element on stage.
also, one making cmd+z, there's no focus on the stage element as well. there's some inconsistent behavior after confirming changes.

**Comment by edenvidal** [comment]
@atulbhatt-system32 @VictoriaShyika it is fixed yet now when i do "cmd+z" it does revert the change text but it doesn't focus back on the element - in need two cmd+z in order to perform both the revert text editing and the focusing on the element.

in general, @atulbhatt-system32 how do we perform the ultimate stress test to find this kind of issues? let's make an issue for that 🙏

**Comment by atulbhatt-system32** [comment]
Yeah @edenvidal I need to create a set of testing we need to do, And I think it should be done twice in a week atleast to ensure any new issues fix aren't causing other new issues.

And Thanks for pointing out that undo and defocus should be a group event. I just missed that while testing.

**Comment by edenvidal** [comment]
@atulbhatt-system32 agree. the testing should be based on the atomic concepts (files, zero-sync, event-based version history, etc.) we can create some ultimate user testing scenarios that encourage trying all of that together.

**Comment by atulbhatt-system32** [comment]
Sure @edenvidal I will have that in place.

**Comment by edenvidal** [comment]
@atulbhatt-system32 yes. it does work now. yet the code it then highlights is the wrong one.

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/e2eb2d67-26b2-4e97-9aa3-b663756b4e1e)

**Comment by atulbhatt-system32** [comment]
Thanks @edenvidal from now on we will have all this things thoroughly tested before moving the code to review. I have created a list of functionalities we need to test before marking a bug as resolved. I'm constantly updating that list. This will also ensure that we don't loose any existing functionality when solving the current one.

**Comment by edenvidal** [comment]
@atulbhatt-system32 please share the list or put in on notion so we can merge forces.

**Comment by atulbhatt-system32** [comment]
sure @edenvidal adding it in developer docs
