### ISSUE TITLE
Improve Background File Sync

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#605]
We sync files and directory state when the focus is out of rnbw app in a fixed interval.

I would like to check if we can improve the trigger functionality using `requestAnimationFrame` instead of setTimeout.

**Comment by VictoriaShyika** [comment]
@atulbhatt-system32 
I tried using `requestAnimationFrame` but it doesn't seem to be suitable for our needs. When using `requestAnimationFrame` sometimes the changes from files don't load and we don't update the data in the app. I also found information about `requestAnimationFrame` potentially causing unnecessary CPU and memory usage.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika thanks for checking it out. I'll close this issue.
