### ISSUE TITLE
Sidebar Issues and Feedbacks

### ISSUE THREAD

**Issue by VictoriaShyika** [rnbwdev/rnbw#627]
- [x] #676

https://github.com/rnbwdev/rnbw/assets/38177419/07ece2af-b3a0-4e87-8367-a1b792dea36d
- [x] Resize Issue when when sidebar is toggled.

https://github.com/rnbwdev/rnbw/assets/38177419/07c5fb2e-f7f2-42cf-b1a7-82429b9daaa0

- [x] when hitting "esc" the sidebar hover-trigger does not work (open) anymore from that moment.
- [x] Sometimes the NavigatorPanel disappears and we can't move between files
- [x] when the sidebar is switched off, there’s a non-clickable stage area that initiates the sidebar slide instead. let’s make the sidebar slide only when reaching the far margin.

- [x] need to remove the radius and borders styles from the sidebar and code and apply plain border-right/left - in both light/dark modes.
- [x] sidebar - node labels are chopped too early
- [x] Adjust the layout styling leading to unwanted gaps between panels
- [x] The sidebar toggle to expand and collapse should be common with sidebar open and close and should work. Currently it's not working on hover also so this also needs to be fixed
- [x] Create consistent styling for Panels using the reference from rnbw.guide code where styling is done using rene. Create components for parts of the panels that can be reused. This would give us consistent styling.
- [x] Make the panel border 1px thick and remove the hover effect from them. Take inspiration from figma for better insights on panel styling
- [x] The separator in action panel "/" gets behind project name. See the second screenshot.
- [x] If the name of the root folder is big then the name of the opened file overlaps the folder name in action panel. It maybe related to the issue above for "/" and solving it may solve this too.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika can you check with the last point I haven't found that behaviour of border-radius yet.

**Comment by edenvidal** [comment]
@VictoriaShyika the sidebar does not open for me when in closed mode." i see like 8px of it. see screenshot

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/c4a7faf7-b535-4fb3-bde0-4a6bdc5298c1)

**Comment by edenvidal** [comment]
- [ ] let's make the files panel resizable as well? i guess it is possible.
- [ ] in addition, let's remove any redundant styling that enforces this distance between the panels. ![Image](https://github.com/rnbwdev/rnbw/assets/13418616/9756df72-b99e-4862-88f2-04abc4b03707)
- [ ] here's a reference to show how clean the ui feels - ![Image](https://github.com/rnbwdev/rnbw/assets/13418616/c0f68b85-6c80-41d4-819f-a236846e2235)

**Comment by atulbhatt-system32** [comment]
Thanks @edenvidal for all the detailed insight. I will see how we can refine it across all the panels based on rnbw.guide and prepare the task according to it.

**Comment by atulbhatt-system32** [comment]
@edenvidal wdym by making files panel resizable? Do you mean vertically resizable?

**Comment by edenvidal** [comment]
yep @atulbhatt-system32 (:

**Comment by edenvidal** [comment]
nice updates! @atulbhatt-system32 i couldn't resize the files panel vertically. and found stuff:
- [ ] when the sidebar is closed - let's make its triggering to happen only when hovering 2px from the left margin?
- [ ] bug - when hitting "esc" the sidebar hover-trigger does not work (open) anymore from that moment.

**Comment by atulbhatt-system32** [comment]
- for vertical resizing we have a different issue as it's a new functionality

- second part I will check

**Comment by atulbhatt-system32** [comment]
@edenvidal you can test the feedback points you shared other than vertical resizing as mentioned we have a different issue for it and we will cover it in the same.

**Comment by edenvidal** [comment]
@atulbhatt-system32 got it. in this case i have a much better idea 💡 - let's remove the predefined height of the files panel and let it adapt? its max-height can stay 50vh. wdyt?

**Comment by atulbhatt-system32** [comment]
also @edenvidal sometimes the file panel automatically shrinks when we click on codeview which shouldn't happens I believe. 

I think it should only shrink or kinda minimize when we click on navigator panel where project root folder name is present.

Also, the current max-height of files panel is already 50vh and we will make it resizable vertically with the same in mind.

**Comment by edenvidal** [comment]
@atulbhatt-system32 I think the files panel should always close when clicking elsewhere. wdyt?

**Comment by edenvidal** [comment]
@atulbhatt-system32 I played with it a bit more, and I agree. closing/opening files should be independent. i believe that it'll work in addition to the adaptive height adjustments
