### ISSUE TITLE
Element Settings

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#634]
- [x] @edenvidal to design

Breakdown of Element Settings:
- [x] Add settings panel
- [x] Display all the attributes of the selected node
- [x] Allow editing of the attributes from the setting tab and then sync it
- [x] Allow editing more attributes to the selected node (list available in HTML Attributes.csv in rfrncs)
- [x] Hide settings panel when multiple nodes are selected

![Image](https://github.com/rnbwdev/rnbw/assets/38177419/82a5a000-f7c6-4d6f-8a03-b836dcdab4d1)

@edenvidal wdyt?

**Comment by atulbhatt-system32** [comment]
Here is the breakdown for styles panel.

Let's say we have a node as below:
`<p style="color:red;font-size:12px;font-weight:700;">`

Now, style panel will be a panel created with react complex tree itself. 

syntax: Style > [ {label:value},{label:value},{label:value}]

Here, when we expand the style, we see its children as all the properties assigned to style attribute.

ex: Style > [{color:red},{font-size:12px}, {font-weight:700}]

Now, label will just be a text and the value will be an input box where we can update the value which syncs across our application.

**Comment by atulbhatt-system32** [comment]
@edenvidal before I breakdown further. Here are some queries:

- Will style panel always be visible, with some minimum height?
- How are we going to add new style properties?
- What is the significance of style1 and style2?
- What is the role of settings panel?

**Comment by atulbhatt-system32** [comment]
Breakdown:

Settings panel will be a panel similar to above panels. Created using react-complex-tree

Settings is basically element or node settings which are its attribute.

In setting we will display all the attributes that the node currently has. Probably available in the node tree or can be added to the nodeTree while parsing and present them here.

Once this is done we will edit the values and they should be updated throughout the app.

**Comment by edenvidal** [comment]
good reference from relate

**Comment by atulbhatt-system32** [comment]
@edenvidal thanks for sharing this. Yeah this is perfect!

**Comment by edenvidal** [comment]
@atulbhatt-system32 is it ready for review?

**Comment by atulbhatt-system32** [comment]
@edenvidal assigned you for the part of design if you think we need any other improvement in terms of ux. Of course the implementation is done to the part where you have tested it.

**Comment by edenvidal** [comment]
- [ ] add handler mechanism for multiple selection of elements
- [ ] show the "x" to remove the setting only on hover

**Comment by edenvidal** [comment]
the design

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/675f63df-0d17-45b3-8fef-4e3c6466dcb0)

**Comment by atulbhatt-system32** [comment]
@edenvidal 

How do we decide whether to show checkbox toggle or cross button for properties?

**Comment by edenvidal** [comment]
@atulbhatt-system32 it's always the toggle. we show the "cross" only when hovering on an empty (no value) setting.
first click - clean value (checkbox-blank)
second click - remove (cross)

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika for this the multiple nodes selection handler is pending. We will need to define the behaviour. You can suggest it. And we can improvise it.

**Comment by atulbhatt-system32** [comment]
@edenvidal how to define the rfrncs part for it and then connect it?

**Comment by edenvidal** [comment]
@atulbhatt-system32 for the moment, let's hide the settings panel when multiple elements are selected. once we resolve the other things, we'll get back to it and handle the multiple editing (we first have to get the "multiple selection" api settled).

**Comment by edenvidal** [comment]
@VictoriaShyika i closed this issue, yet it could be that you'll still need to add to (temporary) functionally of hiding the panel when multiselecting elements
