### ISSUE TITLE
Investigate the use of following packages

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#644]
There are some packages which seems to be not doing some big things for which we would be needing a dependency.

- [x] Buffer
- [x] File Saver
- [x] cx
- [x] make debounce a util and remove the lodash package

**Comment by atulbhatt-system32** [comment]
Buffer is required as a polyfill.

**Comment by edenvidal** [comment]
@atulbhatt-system32 is this done?

**Comment by atulbhatt-system32** [comment]
yes it's done. Will have the code reviewed either by @jasonliu7040 or @VictoriaShyika before merging.
