### ISSUE TITLE
Fix all the suppressed typescript warning that are detected after husky and lint setup

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#666]
Check all the files that have warning and fix as many warnings as possible.

![Image](https://github.com/rnbwdev/rnbw/assets/38177419/608f35d6-6734-4454-ae67-8c3701ce5807)

**Comment by edenvidal** [comment]
@atulbhatt-system32 if this is importnt, get rid of it.

**Comment by edenvidal** [comment]
why should we do it @atulbhatt-system32 ? what's the benefit of it? thanks

**Comment by atulbhatt-system32** [comment]
@edenvidal we should do it for type-safety. JS in not strictly typed so we are using TS in our project to add types to JS code.

Sometimes it is difficult to obtain type specially when the library doesn't provides it. So in this case we will have to manually define the types.

Adding types reduces the chances of errors because of incorrect types. Let's say if a function were to require a number and if pass it string JS may not give error while writing it but if I strictly make the type as number using TS it will throw error in development only preventing the error that would have come during run time.


The other benefit of it is that it gives proper details on what a person should pass to a function and intellisense from vs code also improves.

**Comment by atulbhatt-system32** [comment]
@edenvidal I will close this then. And will have it fixed when we come across those file during any bug resolution.
