### ISSUE TITLE
cannot add comment element

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#674]
This happens when we try to add comment element from the stage by searching comment through the "Add" menu.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika comment element has no ui component however it should get added in codeview

**Comment by edenvidal** [comment]
@atulbhatt-system32 why is comment element name is "#comment" and not "Comment" as it is stated in the references

**Comment by atulbhatt-system32** [comment]
@edenvidal 
I checked it and it turns out the parser was making it #comment and hence it was not getting mapped with references which has comment as the name.

I fixed it. Will be raising its PR.
