### ISSUE TITLE
Add vertical resizing feature to sidebar similar to figma.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#676]
- [x] Vertical resizing should work
- [x] File or workspace panel shouldn't automatically close when focusing on other part of the ui

**Comment by edenvidal** [comment]
@atulbhatt-system32 let's make the files panel's height auto (it shouldn't be that high by default), and the current height will become the max-height.

**Comment by atulbhatt-system32** [comment]
@edenvidal 

is the default height for file panel good enough as shown in the screenshot below?


![Image](https://github.com/rnbwdev/rnbw/assets/38177419/9e5ac350-6604-445e-ba97-390f76ebbef8)
