### ISSUE TITLE
package - raincons

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#690]
- [ ] Try to have raincons installed inside node_modules (can be done via github if possible else it has to be published as an npm package)
- [ ] Replace the path to `raincons` in `svg-icon.config.json` to the locally available raincons from node_moudles.
- [ ] Test the implementation

Here are some references for help:
https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly
<img width="949" alt="image" src="https://github.com/rnbwdev/rnbw/assets/38177419/7b86dab3-baec-4226-ac52-50155c941afb">

**Comment by atulbhatt-system32** [comment]
@stanislavasal For step2 remove the raincons link from the src in the file shown in screenshot and see how it effects the application.

**Comment by edenvidal** [comment]
@VictoriaShyika can i close this one?

**Comment by VictoriaShyika** [comment]
@edenvidal Yes, you can close it.
