### ISSUE TITLE
search

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#709]
- [x] jumpstart - let's enable searching files in the active project
  - [x] add "search" data to jumpstart.csv
  - [x] create the filtering logic around files

Aggregating all the points from the discussion here:

- [x] hitting the j or s key, typing the page's name and selecting it from the file's 
 list.
- [x] no need to show the folder's name inside the route as it's the main context. (I think here by route you mean 'root')
- [x] the search is a "first-class citizen" and needs to be its own standalone command menu, initiated with the s key. this is how it looks like initially
- [ ] "search" is not just displaying and filtering files, it is also a command menu aggregator, means it can display all of the items inside all command menus.
- [x] instead of the jumpstart menu, the search needs to exist inside the do something w key, under the "project" group, at the end
- [ ] let's connect the right icon to the right file type (as done in the files panel using rfrncs)

**Comment by maxdnc** [comment]
Hello,

I have recently been assigned to work on the "search 709" task by Carmen and I am excited to contribute to the project.

I just jumped into the project and I wanted to seek some clarification regarding the task requirements. 

To ensure that I fully understand the task requirements and address the reported issue, I had a few questions:

Can you please provide more details on what kind of search metadata needs to be added to jumpstart.csv? Are there any specific fields or formats that need to be followed? Where to find it ? should I add something there : ? 

![Image](https://github.com/rnbwdev/rnbw/assets/114651071/78f827f5-12e8-4ff1-a0e2-f11ce8786ae0)

Regarding the filtering logic, are there any specific criteria or rules that need to be considered when filtering search results?
Can you please provide more information on the reported issue with the current search functionality? Are there any specific scenarios or use cases where the issue occurs?

if I understand correctly here it is how the filter is processing right ?  : 

- When a user writes into the input to search, the **cmdkSearchContent** state is updated with the input value. This state is part of the **useAppState** hook, which is a global state hook.
- The **useCmdkReferenceData** hook, which is responsible for managing the command key reference data, uses this **cmdkSearchContent** state.
- When **cmdkSearchContent** changes, the useMemo hooks inside **useCmdkReferenceData** are triggered to recompute the **cmdkReferenceAdd** and **cmdkReferenceRename** values.
- These values are computed by the **fileCmdk** and **elementsCmdk** functions, which filter the file tree and valid node tree respectively based on the **cmdkSearchContent**. The filtered results are then used to update the command key reference data.
- The **cmdkReferenceData** is then dispatched to the Redux store using the **setCmdkReferenceData** action. This updates the global state of the application with the new command key reference **data**.
- This new **data** is then used to update the UI, showing the user the results of their search.

Thank you for your time and assistance. I look forward to working with you .

Maxime.

**Comment by edenvidal** [comment]
hey @maxdnc welcome to rnbw!
i updated the issue's description at the top.

yes. you'll need to add "search" to jumpstart.csv.
so, in addition to the current behavior of the jumpstart menu input, which is filtering the menu items, we'd also like to have the jumpstart's input filter through the available active files. so it'll show it like "folder/file.html".
it could be that the main task here is to present "files" group, inside the jumpstart menu, but to trigger their appearance once there is input (the filtering mechanism will then just work)

**Comment by maxdnc** [comment]
Thank you, @edenvidal! 😊

Should the search functionality look like this ? :

![Search Functionality Design](https://github.com/rnbwdev/rnbw/assets/114651071/c330ea31-43e5-4ce8-8436-f6e485c1b131)

To implement this, should i rendering the search results conditionally, only when `cmdkSearchContent` is not an empty string ?

Regarding the available active files, I wanted to confirm if you're referring to the array from `fileTree.ROOT.children`?

Could you please provide some user case examples ? This will help me visualize how users might interact with the feature and the expected results. 

Sorry for asking multiple questions, I want to ensure I fully understand the project and provide the best possible solution. There are indeed many hooks, slices, and other components involved, and I want to make sure everything fits together.

**Comment by edenvidal** [comment]
1. let's place the search inside the `projects` group underneath `open`
2. yes. to implement this, render the search results conditionally.
3. @atulbhatt-system32 `fileTree.ROOT.children` right? i think it is
4. as a user, i am now editing `index.html`, and i want to go to `about.html`, i can do it by...
    - [ ] opening the files panel, navigating to the right file and clicking on it.
    - [ ] hitting the `j` or `s`key, typing the page's name and selecting it from the file's list.

**Comment by atulbhatt-system32** [comment]
@edenvidal yes it has to be derived from fileTree

**Comment by atulbhatt-system32** [comment]
> [@maxdnc](https://github.com/maxdnc)

>    * [ ]  hitting the `j` or `s`key, typing the page's name and selecting it from the file's list.

@edenvidal by hitting "j" do you mean hitting "j" will open jumpstart and from there user select "search".
and hitting "s" will do the above thing in a single step.

Also, search panel is not a different panel but Jumpstart itself which conditionally just shows files and folders?

**Comment by edenvidal** [comment]
- [ ] for some reason, the jumpstart menu is initiated after every almost every event (use the app... design something)
---
i've used it a bit and have some conclusions regarding its ux:

- [ ] the search needs to be its own standalone command menu, initiated with the `s` key. this is how it looks like initially
       ![Image](https://github.com/rnbwdev/rnbw/assets/13418616/ce3c6686-46d3-4e55-badf-e79dd88a1538)


- [ ]

**Comment by ViralRuparel** [comment]
Hello Team,

Viral here. I am a senior fullstack developer, having experience working with Corporates, Startups and OpenSource Projects.

This is the First Task I am working on as an introductory task.

**Comment by edenvidal** [comment]
hey @ViralRuparel (:
looking forward to collab

**Comment by ViralRuparel** [comment]
definitely @atulbhatt-system32  thanks for open to help

**Comment by ViralRuparel** [comment]
I have completed the work for this issue, here is the [PR](https://github.com/rnbwdev/rnbw/pull/820) for the same

**Comment by ViralRuparel** [comment]
Recording of the work output:



https://github.com/rnbwdev/rnbw/assets/21654339/2ebfa0d2-466f-4b5a-ab7f-5e860f3d8715

**Comment by atulbhatt-system32** [comment]
@edenvidal I have aggregated the points from the discussion in the main task. Sharing here to for easy look.

- [ ] hitting the j or s key, typing the page's name and selecting it from the file's 
 list.
- [ ] the search is a "first-class citizen" and needs to be its own standalone command menu, initiated with the s key inside the `do something` **w** key, under the `project` group, at the end.
- [ ] no need to show the folder's name inside the route as it's the main context. 
doubt:(I think here by route you mean 'root')



- [ ] `search` is not just displaying and filtering files, it is also a command menu aggregator, means it can display all of the items inside all command menus.
Need more clarity on how to represent all command menu items in search.

- [ ] let's connect the right icon to the right file type (as done in the files panel using rfrncs)
doubt: I am assuming we can only search files and not folders and for all files we use same type of icon.

**Comment by atulbhatt-system32** [comment]
@edenvidal This is mostly implemented except for the part of search as a command menu aggregator. And the icon needs to be fixed which even @stanislavasal can do.

Other feedbacks you can share.

**Comment by edenvidal** [comment]
<img width="361" alt="Screenshot 2024-06-07 at 12 06 44" src="https://github.com/rnbwdev/rnbw/assets/13418616/a8625948-152b-453a-8501-e030b8f34369">
@atulbhatt-system32 can we fix this too?

**Comment by atulbhatt-system32** [comment]
@stanislavasal you will just need to replace the icon file : `page.svg`
<img width="183" alt="Screenshot 2024-06-07 at 3 43 46 PM" src="https://github.com/rnbwdev/rnbw/assets/38177419/b7ebc914-1aa5-4f28-a064-77199e74273d">

Currently I picked it from raincons. It looks like this:
<img width="853" alt="Screenshot 2024-06-07 at 3 44 32 PM" src="https://github.com/rnbwdev/rnbw/assets/38177419/76c9a804-374e-44c6-8000-a6da994e7242">

@edenvidal I also added `file` icon to the file name. Shall we only show the files listed when anything typed in the search.

**Comment by edenvidal** [comment]
@atulbhatt-system32 of course, it is currently considered a bug as they are presented in the jumpstart menu like this. should show up only by searching at the jumpstart menu or hitting "s"
wdyt?

**Comment by atulbhatt-system32** [comment]
@edenvidal I agree and it only shows files in search results when any text is searched.

**Comment by edenvidal** [comment]
@atulbhatt-system32 i now realize how stupid it is to have the jumpstart menu function as the search. 
let's have the jumpstart continue doing its thing and divide the functionality into a standalone menu. with the placeholder "search". cool?

**Comment by atulbhatt-system32** [comment]
@edenvidal I removed the files search functionality from jumpstart. And we have standalone search already which opens by pressing 'S'.

Now the part from where you want to list not just files in it but all the settings, I want to know how we have to represent it.

**Comment by edenvidal** [comment]
@atulbhatt-system32 why displaying setting inside the search of files? not sure i get it

**Comment by atulbhatt-system32** [comment]
@edenvidal 

<img width="835" alt="Screenshot 2024-06-10 at 11 28 48 AM" src="https://github.com/rnbwdev/rnbw/assets/38177419/ebd96967-50a6-4feb-84cf-d38c7f02db01">

**Comment by edenvidal** [comment]
@atulbhatt-system32 i understand now. so, it seems that the issue is not just with the settings, but with everything, including all the menu items from all command menus.
anyway, i'm not sure if that's the right approach, so let's focus on just searching for files. let's simplify it for now and just make it a search for files. (:

**Comment by atulbhatt-system32** [comment]
@edenvidal it now searches for files. I checked icon was missing added that too in "search"

**Comment by edenvidal** [comment]
looks great. no need for the right info panel when hovering over search results @atulbhatt-system32

**Comment by atulbhatt-system32** [comment]
@edenvidal right info panel is removed
