### ISSUE TITLE
There are some issues in background file sync

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#720]
- [x] When the file loaded on stage is not the default file like (index.html) and the app syncs the file loaded on stage reflects default file instead of the one that was opened. The file panel and even the url reflects the correct file.

**Comment by edenvidal** [comment]
@atulbhatt-system32 @VictoriaShyika what has happened here? how to now test and make sure it is working? need more info.

**Comment by VictoriaShyika** [comment]
@edenvidal Before after opening a file other than index.html and changing focus to another open program on the PC or changing the browser tab, the current opened file would change to index.html, this behavior is solved now.
