### ISSUE TITLE
rnbw consistent selection of element (avoid cases of non selected element)

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#724]
- [x] when deleting an element. have rnbw select the first one below the deleted element (it was working before)
- [x] when the sidebar/code open (after it was closed) the element should be selected in both sidebar/code.

---

- [ ] the right question is - "how does rnbw always, in any case, know what element to select? for example - the active element is gone, for any reason. or, the sidebar/code was closed"

(the question is not "how do we make a fallback for this case to select the last element?")

**Comment by edenvidal** [comment]
@atulbhatt-system32 added some further info about the task. lmk how it is going to be handled 🙏

**Comment by atulbhatt-system32** [comment]
@edenvidal 

On deleting a element node, In figma no node is selected.
According to your instruction in our case we select the immediate next sibling to the node.(the first one below the deleted one)

Let's consider this case:
```
<div> 
  <h1>hello</h1> 
  <h2>world</h2>
  <h3>rnbw</h3> 
</div>
```

Now, if I delete the <h3> what should be selected?

**Comment by edenvidal** [comment]
@atulbhatt-system32 the `h2` 👍

**Comment by edenvidal** [comment]
@atulbhatt-system32 is this relevant?

**Comment by atulbhatt-system32** [comment]
Yes @edenvidal after creating the focus mechanism we need to find and remove all the cases which results in non-focused elements.

**Comment by edenvidal** [comment]
@atulbhatt-system32 let's remove this one or take just what we need from it?

**Comment by atulbhatt-system32** [comment]
> @atulbhatt-system32 let's remove this one or take just what we need from it?

sure

**Comment by atulbhatt-system32** [comment]
I have resolved the issue and haven't found the occurrence of unselected node. The fallback is already there but sometimes the issue is caused because of other reasons.

Like last time the issue was because the stage was not focused so the event listener that is attached to stage wasn't working.
