### ISSUE TITLE
update: The favicon should respond to browser theme.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#733]
The favicon should be shown with respect to the browser theme. Browser theme can be dark, light, or device based. 

When it's light favicon should use dark icon and when it's dark favicon will be light to be contrasting.
Now, the third case when the browser's theme is based on device we toggle it according to the System theme.

Check the video below for better understanding.

https://github.com/rnbwdev/rnbw/assets/38177419/b45ad959-1ec2-4ddb-b943-91785af5df1e

**Comment by edenvidal** [comment]
also, let's update to the recent favicon from figma @edenvidal @atulbhatt-system32

**Comment by atulbhatt-system32** [comment]
@edenvidal can you please point me to the latest icon in figma by mentioning me in the comment there.

**Comment by edenvidal** [comment]
[there it is](https://www.figma.com/file/cQZej1OS6VkvEGzfNULZlB/rnbw?type=design&node-id=4233%3A890&mode=design&t=DXmpeJPowpnQYFcT-1)
