### ISSUE TITLE
Make History Management Consistent and Error Free

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#736]
- [x] Define the rules for History Management (Figma as a reference)
- [x] Understand the existing history implementation in rnbw
- [x] Create instructions on how to write an event that correctly registers the history
- [x] Check the history implementation with undo and redo
- [ ] Do stress testing of history management

**Comment by atulbhatt-system32** [comment]
![Image](https://github.com/rnbwdev/rnbw/assets/38177419/0ebad843-f77d-422a-a74a-ced5c3ff2b78)
@VictoriaShyika

**Comment by VictoriaShyika** [comment]
Rules for History Management:

The behavior of a file in rnbw is similar to a page in Figma:
- file _selection_ changing during redo/undo;
- _recently opened_ file is re-opened on redo/undo;
- file _deleting_ undo (it may not be possible in File System);
- _adding, renaming, copy, past, dnd_ should be undoable (now it is implemented in rnbw);

Nodes behavior:
- _selecting_ node changing while undo/redo (now it is implemented in rnbw);
- _add, past, delete, dnd, duplicate_, etc. - should undo in one action (now it is implemented in rnbw with 2 actions: collapse selected node, undo action);
- _group and ungroup_ should undo/redo in one action (now it is more than 2 actions);
- undo after _editing from stage_ should return in editable mode, next undo should change value to before state;
- _expanding and collapsing_ nodes should not be undoable actions in figma (now they are);

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika This is a great comparison of behaviours.

We can start fixing the implementation from the node. As for files it's almost good. And it's the node that user will be interacting the most with.

However, my main intent was understanding how we are managing the implementation of the current behaviour.

Like using redux-undo and grouping actions in that. Is that consistent.

**Comment by VictoriaShyika** [comment]
@atulbhatt-system32 
History is registered in the reducer. We use a group action so that a set of actions is registered as a single action, so we can manage it. 
We can also filter our actions and log only necessary actions. Also we have onUndo and onRedo functions and we manage the types there, I think we need to make some corrections in these functions and we can achieve the desired behavior. We can check the value being logged and handle errors if some unexpected value is added.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika 

I think comparing the behaviour of pages in figma and project or File tree in rnbw is not a correct comparison.
They both are very different.

For instance, Figma pages are entity while in project there is a folder which can have files.

So for the behaviour or project we need to look into the behaviour of the VS code. Wdyt?

**Comment by VictoriaShyika** [comment]
History node or file flow depending on `activePanel` value.

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika the issue happens on redo after undo.

**Comment by edenvidal** [comment]
@atulbhatt-system32 @VictoriaShyika what is the status of this issue? can we resolve/close it?

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika there was an issue when changing content in codeview while the save operation was happening. Can you check that again!

**Comment by atulbhatt-system32** [comment]
@vicki29 On undo of move the nodetree isn't focused with the correct node.

**Comment by edenvidal** [comment]
@atulbhatt-system32 is this relevant?

**Comment by atulbhatt-system32** [comment]
We can close this
