### ISSUE TITLE
Segregate and Categorise SideEffects

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#743]
Currently we have separate hooks for performing different cateogories of actions. Like File actions, Node Actions, etc.

However, there are various side effects that run on various actions such as clicking on codeview changes active panel to code and there are many other actions that run as sideeffect to changing of actions panel. And we need to categorise them for other developers to also expand their functionalities based on these sideeffects.

**Comment by edenvidal** [comment]
@atulbhatt-system32 let's make it happen.

**Comment by edenvidal** [comment]
@atulbhatt-system32 same relevant [in here](https://github.com/rnbwdev/rnbw/issues/666#issuecomment-2063158702) (:

**Comment by atulbhatt-system32** [comment]
@edenvidal removing it. Will cover this when we will be restructuring API.
