### ISSUE TITLE
code

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#771]
- [x] currently, the code is wrapped inside the codeview box. in monaco, there should be a feature to have the code wrapped, for better coding experience. it makes the internal bounding box of the code view unlimited so that code won't wrap. (basically, try resizing the same code in rnbw and in vscode to compare how the text wrap or not wrap)
- [x] formatting - code formatting should be "on" by default and we can even remove it as a settings. (let's do it)
  - [x] instead, format code will become an action. you can select an element and ask to format it via the "do something" menu. the result will be a formatted code.
  - [x] code can come in many ways, yet when rainbow is adding or changing code, it will always be in the formatted way.

**Comment by artemklishch** [comment]
Hello @atulbhatt-system32 !
I was assigned to the task. 
But i don't get it what is the issue from the description. 
Could you please make a video with sharing the screen what it is and explaination. Or let's find a way to have a call.
Thanks!

**Comment by atulbhatt-system32** [comment]
@artemklishch 

This task has 2 subtasks and they can be solved in an independent PR.

I will explain the 2nd task for now.
In the image below you see we have a toggle for Format Code. 

I'm breaking this task down for you in actionable steps.

- [ ] Now, we need to keep this toggle "on" by default. Basically, we don't need a toggle now. Whatever operation uses this toggle should always by default format the code.
- [ ] This toggle menu option should be removed from the "UI" - Jumpstart menu

You can cover upto this part. Making format code an action you can skip for now. I will update you on that after you are done with the above 2 points in a PR.



![Image](https://github.com/rnbwdev/rnbw/assets/38177419/b661af15-9e34-479b-b227-6c307108c873)

**Comment by atulbhatt-system32** [comment]
@artemklishch 
For the first part of the task you need to know that we have a code editor in rnbw, which you can see on the right of screenshot above.

This is a library called react-monaco which vs code also uses internally.

Now, the task may seem like a mammoth but it's simple. What we need to do is that we need to provide an option to toggle the wordwrap configuration of the editor.

wordwrap should be false by default which is currently true. And in settings we should have a toggle to change it.

So bascially in above task you remove format code toggle and in this you add a word-wrap toggle. The shortcut for it can be `option/alt` + `z`

**Comment by artemklishch** [comment]
> @artemklishch For the first part of the task you need to know that we have a code editor in rnbw, which you can see on the right of screenshot above.
> 
> This is a library called react-monaco which vs code also uses internally.
> 
> Now, the task may seem like a mammoth but it's simple. What we need to do is that we need to provide an option to toggle the wordwrap configuration of the editor.
> 
> wordwrap should be false by default which is currently true. And in settings we should have a toggle to change it.
> 
> So bascially in above task you remove format code toggle and in this you add a word-wrap toggle. The shortcut for it can be `option/alt` + `z`

I have a question.
Should i start working on this task after you merge previous PR?

**Comment by atulbhatt-system32** [comment]
@artemklishch you can continue on code wrap part.
