### ISSUE TITLE
🌈Turn Into - custom rnbw-action🌈

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#775]
"turn into" is a custom action and therefore is should live inside rnbw, but as a convention, as an internal demo, to set a standard for all external actions.

- [x] turn it into a rnbw-action.
- [x] it currently removes the content + attributes of the element. let's keep it though.
- [x] enabling turning into for multiple elements. @atulbhatt-system32 how do we make an api call for multiple elements in which a complex action such as "turn into" can hook into. it currently won't work.
- [x] when the command menu it becoming the "turn into" menu.
  - [x] let's have a "back" icon that goes back to the "do something"
  - [x] let's remove the text written inside the search, since it could be that you've gotten into "turn into" by typing "tu...".

**Comment by edenvidal** [comment]
@vicki29 see unchecked boxes

**Comment by edenvidal** [comment]
@vicki29 check it out

**Comment by vicki29** [comment]
@edenvidal 
Could you please check again in which cases this happens, because on my side the tag content and attributes does not remove.

**Comment by edenvidal** [comment]
true! (:
