### ISSUE TITLE
sidebar items

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#776]
- [x] When doing multi-selection from node-tree by pressing cmd or shift the node should not expand.
- [ ] The menu item in react complex tree doesn't take full width sometimes and therefore there's horizontal scrolling happening inside the sidebar bounds.

**Comment by atulbhatt-system32** [comment]
@edenvidal So if the tree expands more than the width of the sidebar shall we increase the sidebar so that it doesn't scrolls?

**Comment by edenvidal** [comment]
@atulbhatt-system32 nope. i think figma is a good reference. it just doesn't internally scroll

**Comment by atulbhatt-system32** [comment]
@edenvidal done
