### ISSUE TITLE
rnbw api+actions / design+implementation

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#792]
- [x] Create a structure for the actions
- [x] Basic Actions in `Do something menu` should match the APIs define in develop.html of rnbw.design (create, update, delete)
- [x] Custom Actions will become the part of `Custom` Section in `Do Something" menu.`
- [x] `Turn Into` will be a part of the Custom actions
- [x] Implement the APIs

**Comment by atulbhatt-system32** [comment]
| Basic Action | API |
|-------------|-----|
| Cut               | `rnbw.element.cut()` |
| Copy            | `rnbw.element.copy()` |
| Paste            | `rnbw.element.paste()` |
| Span Paste  | `rnbw.element.plainPaste()`|
| Delete          | `rnbw.element.delete()`|
| Duplicate     | `rnbw.element.duplicate()` |
| Group           | `rnbw.element.group()` |
| Ungroup       |`rnbw.element.ungroup()`|
| Format          | `rnbw.element.?()`|

**Comment by atulbhatt-system32** [comment]
### Rnbw Actions

Actions in rnbw are created with the help of rnbw APIs.
Rnbw has 2 type of actions- internal and external.

Actions reside in the root directory of rnbw. Every action is a file with its definition.

example: `rnbw > actions > turnInto.action.js`

**Comment by edenvidal** [comment]
@atulbhatt-system32 this looks great. actions are also for files or the entire project context, not just elements. how do we represent that ?

**Comment by atulbhatt-system32** [comment]
@edenvidal updated the table to represent files also

**Comment by atulbhatt-system32** [comment]
### Rnbw Actions (update)

Actions in rnbw are created with the help of rnbw APIs.
Rnbw has 2 type of actions- internal and external.

Actions reside in the root directory of rnbw. Every action is a file with its definition.

Rnbw APIs are exposed via a custom-hook called `useRnbw()`.

Therefore, to use a custom hook we either need to have a react component or another custom hook.

Now, to create any new actions using the APIs we would need to create another custom hook. Actions reside in the root directory of rnbw. Every action is a file with its definition.

example: rnbw > actions > `useTurnInto.action.tsx`

Here's an example of how a rnbw action would look like.

`
export default function useTurnInto() {
  const rnbw = useRnbw();
  const selectedElements = rnbw.elements.getSelectedElements();

  function turnInto(tagName: string) {
    selectedElements.forEach((uid) => {
      //replace the tag name
      const node = rnbw.elements.getElement(uid);
      if (node) {
        const { startCol, startLine, endCol, endLine } =
          node.data.sourceCodeLocation;

        const edit = {
          range: new Range(startLine, startCol, endLine, endCol),
          text: `<${tagName}>${node.data.content}</${tagName}>`,
        };
        helperModel.applyEdits([edit]);
      }
    });
  }
  return { turnInto };
}
`

**Comment by atulbhatt-system32** [comment]
Another example of a custom action.

```
export default function useRemoveAllAttributes() {
  const rnbw = useRnbw();
  function removeAllAttributes() {
    const selectedElements = rnbw.elements.getSelectedElements();
    selectedElements.forEach((uid) => {
      const node = rnbw.elements.getElement(uid);
      if (node) {
        const { startCol, startLine, endCol, endLine } =
          node.data.sourceCodeLocation;

        const edit = {
          range: new Range(startLine, startCol, endLine, endCol),
          text: `<${node.data.tagName}>${node.data.content}</${node.data.tagName}>`,
        };
        helperModel.applyEdits([edit]);
      }
    });
  }

  const config = {
    name: "Remove All Attributes",
    action: removeAllAttributes,
    description: "Remove all attributes from selected elements",
    shortcuts: ["cmd+alt+a"],
  };

  return config;
}

```

**Comment by atulbhatt-system32** [comment]
This is an example of action created for files.
```

export default function useRemoveEmptyFolders() {
  const rnbw = useRnbw();
  async function removeEmptyFolders() {
    const fileTree = rnbw.files.getRootTree();
    const emptyFolders: string[] = [];
    Object.keys(fileTree).forEach(async (key) => {
      const node = fileTree[key];
      if (!node.isEntity && node.children.length === 0) {
        if (node.children.length === 0) {
          emptyFolders.push(node.uid);
        }
      }
    });

    if (emptyFolders.length === 0) {
      return;
    }
    try {
      await rnbw.files.remove({ uids: emptyFolders });
    } catch (err) {
      console.error(err);
    }
  }

  const config = {
    name: "Remove Empty Folders",
    action: removeEmptyFolders,
    description: "Remove all empty folders from the project",
    shortcuts: ["cmd+shift+e"],
  };
  return config;
}
```

**Comment by atulbhatt-system32** [comment]
@edenvidal these are just example. But these are very close to how they will look.

**Comment by edenvidal** [comment]
@atulbhatt-system32, i like this. can you condense all the info here into a readable "actions" section in the design? include the relevant examples for each part 🙌 and the appropriate changes to the api reference section. for example, let's make it as complete as possible before making our code mirror it.

**Comment by atulbhatt-system32** [comment]
sure @edenvidal I will update it in the design.

**Comment by vicki29** [comment]
We need to improve some apis:
Elements: move, group/ungroup.
Files: copy, duplicate, rename.

**Comment by atulbhatt-system32** [comment]
@edenvidal I'm updating docs to match current latest APIs and also will be testing the functionalities on the way.
