### ISSUE TITLE
settings zero sync consistency

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#804]
js changes need to be taken place immediately, how do we do that

how to reproduce - 
1. change the source of an svg-icon. it won't update unless saving and reloading the document.
2. change the source of a js file. it won't update.
3. change filename on local won't change on rnbw

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/2232d761-0727-43aa-8c96-ceeb2a496688)

**Comment by edenvidal** [comment]
@atulbhatt-system32 can you reproduce and provide some info about the cause of it? thanks.

**Comment by atulbhatt-system32** [comment]
1. svg-icon is a web component and we can't update it without reloading as it needs to runs JS which we can't trigger manually.
2. Similar case is with changing the source of JS file. 

1 and 2 both fall in the category of live update. They all are part of issue #779 

3. I need to understand steps to reproduce.
