### ISSUE TITLE
Make a single function to find out the node to be focused after completing an operation

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#809]
Currently for every single action we have a different function to find a node to be selected.

![Image](https://github.com/rnbwdev/rnbw/assets/38177419/fe9421ce-31e9-4f41-b81d-b411cbe3e8df)

We need to think of a better approach to solve this.

**Comment by edenvidal** [comment]
@atulbhatt-system32 is this relevant?

**Comment by atulbhatt-system32** [comment]
Yes @edenvidal this is relevant.
