### ISSUE TITLE
Node focus after performing an action pending for moving of elements

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#833]

**Comment by edenvidal** [comment]
@atulbhatt-system32 it doesn't work in so many cases.

- [ ] right from the beginning when adding an element  - this element isn't focuses

**Comment by edenvidal** [comment]
@atulbhatt-system32 please merge the content of this issue with your breakdown

**Comment by atulbhatt-system32** [comment]
To move nodes, we need 3 things:

1. The nodes that are to be moved.
2. The target node where they will be moved.
3. The position where it is moved in case of Drag and Drop.

The main thing which we need to calculate is the path of the target node. Because after move operation is completed the nodes that were moved will either be below the target node or inside the target node.

Let's take an example:

Target Node Path: ROOT.html_1.body_2.div_1.div_2


The path here denotes the hierarchy and position of each element in that hierarchy.

ROOT is the topmost parent.
html is the first child of ROOT.
body is the 2nd child of html. (head was the first)
and so on.


The target node path may not always change. Let's take an example:

Move Node: ROOT.html_1.body_2.div_1.div_4.legend_9

Let's now compare it with target node path.

ROOT.html_1.body_2.div_1.div_2
ROOT.html_1.body_2.div_1.div_4.legend_9

Now, the `legend_9` will be moved to `div_2`.  But this won't affect the target path at all it will remain the same.

To make it more clear let's take an example where the moving of a node changes the target node.

<img width="323" alt="image" src="https://github.com/rnbwdev/rnbw/assets/38177419/a82a112a-1eef-478e-babc-5609eea67635">

In the example above:
Target Node Path: ROOT.html_1.body_2.div_1.div_1.div_2.bdi_7
Moved Node Path: ROOT.html_1.body_2.div_1.div_1.div_2.h4_4

Here both the nodes are siblings. They both are the children of `div_2`.
Moved node `h4_4` is the 4th child and `bdi_7` is the 7th child respectively.

So if I move `h4_4` all the siblings below it will have their positions shift by 1. And this will affect the target node too.
Now the target node will become.
ROOT.html_1.body_2.div_1.div_1.div_2.bdi_6

**Comment by atulbhatt-system32** [comment]
![Image](https://github.com/rnbwdev/rnbw/assets/38177419/5bc97fa2-9cd2-4c78-afea-6229a0b0694b)

    const targetPath = validNodeTree[focusedItem].uniqueNodePath;
    let movedNodePaths = sortedUids
      .slice(focusedNodeIndexInSortedUids + 1)
      .map((uid) => validNodeTree[uid].uniqueNodePath) as string[];

    //make sure the movedNodePaths are unique and not undefined
    movedNodePaths = Array.from(new Set(movedNodePaths)).filter(
      (path) => typeof path === "string",
    );
    if (!targetPath) return;

    //we initialize the updatedTargetNodePath with the targetPath
    let updatedTargetNodePath = targetPath;

    let pathSubtractor = 1;
    let prevCommonPath = "";
    /*Example:
     Target Node Path: ROOT.html_1.body_2.div_1.div_1.div_9.div_2.div_1
     Moved Node Path: ROOT.html_1.body_2.div_1.div_1.h2_4
     */
    movedNodePaths.forEach((path) => {
      const movedPathArr = path.split(".");
      //[ROOT,html_1,body_2,div_1,div_1, div_9, div_2, div_1]
      const targetPathArr = updatedTargetNodePath.split(".");
      //[ROOT,html_1,body_2,div_1,div_1,h2_4]
      const movedPathLength = movedPathArr.length;
      const targetPathLength = targetPathArr.length;

      /* We find minimum path length so that 
      we only find the common path*/

      const minPathLength = Math.min(movedPathLength, targetPathLength);
      let commonPath = "";
      //ROOT.html_1.body_2.div_1.div_1

      /*we are trying to find the common path between the moved node 
      and the target node to find the divergent node */
      for (let i = 0; i < minPathLength; i++) {
        /* till the paths are the same 
        we keep adding the path to the common path */
        if (movedPathArr[i] === targetPathArr[i]) {
          commonPath += `${movedPathArr[i]}.`;
        } else {
          /* Divergent nodes are the nodes where 
          both target and moved nodes are siblings */
          const divergentMovedNode = movedPathArr[i];
          const divergentTargetNode = targetPathArr[i];

          /* We need to check if the diverged moved node is 
          before the diverged target node*/
          const divergentMovedNodeIndex = parseInt(
            divergentMovedNode.split("_")[1],
          );
          let divergentTargetNodeIndex = parseInt(
            divergentTargetNode.split("_")[1],
          );

          /* If the diverged moved node is before the diverged target node
          we need to subtract the pathSubtractor from the diverged target node index */
          if (divergentMovedNodeIndex < divergentTargetNodeIndex) {
            let remainingPath = "";
            //.div_2.div_1

            /*When the diverged target node is not the last node*/
            if (i + 1 < targetPathLength) {
              remainingPath = `.${targetPathArr.slice(i + 1).join(".")}`;
            }
            if (prevCommonPath !== commonPath) {
              pathSubtractor = 1;
            } else {
              prevCommonPath = commonPath;
              pathSubtractor++;
            }

            /* We update the diverged target node index by 
            subtracting the pathSubtractor which is always 1 
            if we are moving only 1 node */
            divergentTargetNodeIndex -= pathSubtractor;

            /* construct the uncommon path with updated divergent target node index */
            const updatedDivergentNode = `${divergentTargetNode.split("_")[0]}_${divergentTargetNodeIndex}${remainingPath}`;

            /* update the target node path with the updated divergent node */
            updatedTargetNodePath = `${commonPath}${updatedDivergentNode}`;
          }

          break;
        }
      }
    });

    //get selecteduids nodes name
    const movedNodeNames = selectedUids.map(
      (uid) => validNodeTree[uid].displayName,
    );

**Comment by edenvidal** [comment]
@atulbhatt-system32 what's this?

**Comment by atulbhatt-system32** [comment]
We can close this.
