### ISSUE TITLE
When grouping for the first time editor removes the group node

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#840]

**Comment by edenvidal** [comment]
@atulbhatt-system32 for some weird reason. it seems that it is possible to ungroup elements like h1, which is ok, but even then, it should at least keep the content that held inside. and even them, there's no focuses element after the action is done.

**Comment by edenvidal** [comment]
@atulbhatt-system32 for some weird reason. it seems that it is possible to ungroup elements like h1, which is ok, but even then, it should at least keep the content that is held inside. and even then, there's no focus element after the action.

**Comment by atulbhatt-system32** [comment]
@edenvidal thanks for pointing out

**Comment by atulbhatt-system32** [comment]
@edenvidal this has been fixed and now ungroup of text elements extracts the text out. Focusing issue will all be covered in its separate issue.
