### ISSUE TITLE
Pressing escape while creating a file or folder to abort renaming crashes rnbw

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#850]
![Image](https://github.com/rnbwdev/rnbw/assets/38177419/115b069b-9aa5-4553-a97c-850937a0253d)

**Comment by edenvidal** [comment]
@atulbhatt-system32 there's no need to provide a name when creating a file. rnbw should give some name like "untitled-1" ...

**Comment by atulbhatt-system32** [comment]
@edenvidal the behaviour is taken from vs code where it provides user with the prompt to create file.

In Rnbw, by default user is presented with the name `untitled` if he doesn't wish to specify a name. He just needs to press enter to continue and rnbw handles it.

**Comment by edenvidal** [comment]
@atulbhatt-system32, so there's no need to initialize editing mode at all.
the file is created and then focused. that's it.
