### ISSUE TITLE
code lose context after editing

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#875]
@atulbhatt-system32 we still have the issue of code losing context once making an edit. can you fix this?

**Comment by atulbhatt-system32** [comment]
@edenvidal for this too we will have to remove the functionality of refreshing on JS change entirely. As the refresh happens and the stage is focused back. This I had mentioned before also when the JS refresh was implemented.

**Comment by edenvidal** [comment]
@atulbhatt-system32 sounds good. let's remove itץ

**Comment by atulbhatt-system32** [comment]
@edenvidal pushed the changes to dev for this.

**Comment by edenvidal** [comment]
<img width="1438" alt="Screenshot 2024-07-08 at 17 00 19" src="https://github.com/rnbwdev/rnbw/assets/13418616/de532943-b9eb-48e5-8e10-d990ed55d559">
i think something is now messed up as i am trying to remove add/remove/change elements on the design, they reflect on the code but not on the design. i am pretty sure it is related to this.

**Comment by atulbhatt-system32** [comment]
@edenvidal is it a private repo? I can't find it. Also is it linked to JS somehow whatever you are duplicating?

**Comment by edenvidal** [comment]
@atulbhatt-system32 i've sent you the files. and yes, there's linked js in there ✌️

**Comment by edenvidal** [comment]
@atulbhatt-system32 yes. as mentioned. I can see that this functionality is kinda removed. but now there's new issue -

i'm having trouble making changes to the design. when i try to add, remove, or change elements, they show up in the code but not in the design itself. i think this issue is related to javascript because it seems to only happen when js is involved. it's possible that the functionality is still connected to other parts of the system

**Comment by atulbhatt-system32** [comment]
@edenvidal there will be a tradeoff between JS refresh context loosing issue or the current one. Both can't be achieved currently at the same time!

**Comment by edenvidal** [comment]
@atulbhatt-system32 i don't understand - didn't we agree to remove the js refresh functionality?!

> @atulbhatt-system32 sounds good. let's remove it.

**Comment by atulbhatt-system32** [comment]
@edenvidal 
The problem you are facing that when you duplicate your element which is linked to JS (i.e. JS runs on page load and updates your element) doesn't works on duplicating because JS will not run again on duplicating. So when we were doing JS refresh before it was updating but now it won't as we removed the functionality!

**Comment by edenvidal** [comment]
yes, @atulbhatt-system32 , which is great. but there is this bug described in here that has nothing to do with what you're describing. please, take a sec to try to reproduce and get to the bottom of what im describing here:

> @atulbhatt-system32 i think something is now messed up as i am trying to add/remove/change elements on the design, they reflect on the code but not on the design. i am pretty sure it is related to this. try editing this page in rnbw https://edenvidal.com/articles (download it) - duplicate the articles

**Comment by atulbhatt-system32** [comment]
@edenvidal I checked this. I think you are right, it's a different type of issue but it's not related to JS refresh being removed.
On other pages duplication works correctly or even the copy paste and add works correctly except in this specific case.

This is not an existing issue, it's a new issue we have identified. I will try to solve it for this instance.

**Comment by edenvidal** [comment]
thanks @atulbhatt-system32 this is awesome! (:
