### ISSUE TITLE
when deleting an element from a page where there is js elements. it refreshed the page violently - let's cancel this

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#876]

**Comment by atulbhatt-system32** [comment]
@edenvidal for this we will have to remove the functionality of refreshing on JS change entirely.

**Comment by edenvidal** [comment]
@atulbhatt-system32 sounds good. let's remove it entirely 🙏 @edenvidal and @stanislavasal we'll make a button that refreshed the design "on demand" later.
