### ISSUE TITLE
when deleting an element, then cmd+z, then deleting the element again (or applying anything to it) wouldn't work, the selection is visible but not functioning

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#877]
@atulbhatt-system32 can you help with that?

**Comment by atulbhatt-system32** [comment]
@edenvidal  
Sure I will check it and try to fix it!

**Comment by atulbhatt-system32** [comment]
@edenvidal I have pushed some changes to fix it. Took a good amount of time so should be working correctly now.
