### ISSUE TITLE
deploy to github

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#878]
@atulbhatt-system32 small think we need help with (:

i removed vercel, both on rnbw.design and rnbw.dev (it is not worth it).
so i configured rnbw.design domain for github. would love your help in making the main automatically deploy in there as it previously was🙏

![Image](https://github.com/rnbwdev/rnbw/assets/13418616/671b8e60-f5f0-4562-a98b-4e1fb81710ae)

**Comment by atulbhatt-system32** [comment]
sure @edenvidal will check it tonight or tomorrow morning

**Comment by atulbhatt-system32** [comment]
@edenvidal it's done. Now push on "main" will deploy the main

**Comment by edenvidal** [comment]
thanks @atulbhatt-system32
